import os

from config import datasets_cache_dir

TASKS = [
    {'taskId': 1,'repo': "InstaDeepAI/nucleotide_transformer_downstream_tasks_revised", 'name': "promoter_all", 'alias': "promoter_all", 'len': 300, 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 2, 'data_alias': 'Promoter (all)'},
    {'taskId': 2,'repo': "InstaDeepAI/nucleotide_transformer_downstream_tasks_revised", 'name': "promoter_tata", 'alias': "promoter_tata", 'len': 300, 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 2, 'data_alias': 'Promoter (TATA)'},
    {'taskId': 3,'repo': "InstaDeepAI/nucleotide_transformer_downstream_tasks_revised", 'name': "promoter_no_tata", 'alias': "promoter_no_tata", 'len': 300, 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 2, 'data_alias': 'Promoter (non-TATA)'},
    {'taskId': 4,'repo': "InstaDeepAI/nucleotide_transformer_downstream_tasks_revised", 'name': "enhancers", 'alias': "enhancers", 'len': 400, 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 2, 'data_alias': 'Enhancers'},
    {'taskId': 5,'repo': "InstaDeepAI/nucleotide_transformer_downstream_tasks_revised", 'name': "enhancers_types", 'alias': "enhancers_types", 'len': 400, 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 3, 'data_alias': 'Enhancers (types)'},
    {'taskId': 6,'repo': "InstaDeepAI/nucleotide_transformer_downstream_tasks_revised", 'name': "splice_sites_all", 'alias': "splice_sites_all", 'len': 600, 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 3, 'data_alias': 'Splice Sites (all)'},
    {'taskId': 7,'repo': "InstaDeepAI/nucleotide_transformer_downstream_tasks_revised", 'name': "splice_sites_acceptors", 'alias': "splice_sites_acceptors", 'len': 600, 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 2, 'data_alias': 'Splice Sites (acceptors)'},
    {'taskId': 8,'repo': "InstaDeepAI/nucleotide_transformer_downstream_tasks_revised", 'name': "splice_sites_donors", 'alias': "splice_sites_donors", 'len': 600, 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 2, 'data_alias': 'Splice Sites (donors)'},
    {'taskId': 9,'repo': "InstaDeepAI/nucleotide_transformer_downstream_tasks_revised", 'name': "H2AFZ", 'alias': "H2AFZ", 'len': 1000, 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 2, 'data_alias': 'H2AFZ'},
    {'taskId': 10,'repo': "InstaDeepAI/nucleotide_transformer_downstream_tasks_revised", 'name': "H3K27ac", 'alias': "H3K27ac", 'len': 1000, 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 2, 'data_alias': 'H3K27ac'},
    {'taskId': 11,'repo': "InstaDeepAI/nucleotide_transformer_downstream_tasks_revised", 'name': "H3K27me3", 'alias': "H3K27me3", 'len': 1000, 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 2, 'data_alias': 'H3K27me3'},
    {'taskId': 12,'repo': "InstaDeepAI/nucleotide_transformer_downstream_tasks_revised", 'name': "H3K36me3", 'alias': "H3K36me3", 'len': 1000, 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 2, 'data_alias': 'H3K36me3'},
    {'taskId': 13,'repo': "InstaDeepAI/nucleotide_transformer_downstream_tasks_revised", 'name': "H3K4me1", 'alias': "H3K4me1", 'len': 1000, 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 2, 'data_alias': 'H3K4me1'},
    {'taskId': 14,'repo': "InstaDeepAI/nucleotide_transformer_downstream_tasks_revised", 'name': "H3K4me2", 'alias': "H3K4me2", 'len': 1000, 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 2, 'data_alias': 'H3K4me2'},
    {'taskId': 15,'repo': "InstaDeepAI/nucleotide_transformer_downstream_tasks_revised", 'name': "H3K4me3", 'alias': "H3K4me3", 'len': 1000, 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 2, 'data_alias': 'H3K4me3'},
    {'taskId': 16,'repo': "InstaDeepAI/nucleotide_transformer_downstream_tasks_revised", 'name': "H3K9ac", 'alias': "H3K9ac", 'len': 1000, 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 2, 'data_alias': 'H3K9ac'},
    {'taskId': 17,'repo': "InstaDeepAI/nucleotide_transformer_downstream_tasks_revised", 'name': "H3K9me3", 'alias': "H3K9me3", 'len': 1000, 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 2, 'data_alias': 'H3K9me3'},
    {'taskId': 18,'repo': "InstaDeepAI/nucleotide_transformer_downstream_tasks_revised", 'name': "H4K20me1", 'alias': "H4K20me1", 'len': 1000, 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 2, 'data_alias': 'H4K20me1'},
    {'taskId': 19,'repo': "katarinagresova/Genomic_Benchmarks_human_ensembl_regulatory", 'name': "", 'alias': "gb_human_ensembl_regulatory", 'len': 600, 'sequence_feature': 'seq', 'label_feature': 'label', 'num_labels': 3, 'data_alias': 'Human Ensemble (regulatory)'}, #len 80 - 800
    {'taskId': 20,'repo': "katarinagresova/Genomic_Benchmarks_demo_human_or_worm", 'name': "", 'alias': "gb_demo_human_or_worm", 'len': 200, 'sequence_feature': 'seq', 'label_feature': 'label', 'num_labels': 2, 'data_alias': 'Human or Worm (Demo)'},
    {'taskId': 21,'repo': "katarinagresova/Genomic_Benchmarks_human_ocr_ensembl", 'name': "", 'alias': "gb_human_ocr_ensembl", 'len': 400, 'sequence_feature': 'seq', 'label_feature': 'label', 'num_labels': 2, 'data_alias': 'Human Ensemble (ocr)'}, #80-600
    {'taskId': 22,'repo': "katarinagresova/Genomic_Benchmarks_drosophila_enhancers_stark", 'name': "", 'alias': "gb_drosophila_enhancers_stark", 'len': 1000, 'sequence_feature': 'seq', 'label_feature': 'label', 'num_labels': 2, 'data_alias': 'Enhancers (drosophila)'}, #500-2500
    {'taskId': 23,'repo': "katarinagresova/Genomic_Benchmarks_dummy_mouse_enhancers_ensembl", 'name': "", 'alias': "gb_dummy_mouse_enhancers_ensembl", 'len': 1000, 'sequence_feature': 'seq', 'label_feature': 'label', 'num_labels': 2, 'data_alias': 'Enhancers (mouse)'}, #1000-4000
    {'taskId': 24,'repo': "katarinagresova/Genomic_Benchmarks_demo_coding_vs_intergenomic_seqs", 'name': "", 'alias': "gb_demo_coding_vs_intergenomic_seqs", 'len': 200, 'sequence_feature': 'seq', 'label_feature': 'label', 'num_labels': 2, 'data_alias': 'Coding vs Intergenomic Seq.'},
    {'taskId': 25,'repo': "katarinagresova/Genomic_Benchmarks_human_enhancers_ensembl", 'name': "", 'alias': "gb_human_enhancers_ensembl", 'len': 600, 'sequence_feature': 'seq', 'label_feature': 'label', 'num_labels': 2, 'data_alias': 'Enhancers (human ensemble)'}, #1-600
    {'taskId': 26,'repo': "katarinagresova/Genomic_Benchmarks_human_enhancers_cohn", 'name': "", 'alias': "gb_human_enhancers_cohn", 'len': 500, 'sequence_feature': 'seq', 'label_feature': 'label', 'num_labels': 2, 'data_alias': 'Enhancers (human cohn)'},
    {'taskId': 27,'repo': "katarinagresova/Genomic_Benchmarks_human_nontata_promoters", 'name': "", 'alias': "gb_human_nontata_promoters", 'len': 251, 'sequence_feature': 'seq', 'label_feature': 'label', 'num_labels': 2, 'data_alias': 'Promoter Human (no TATA)'},
    {'taskId': 28,'repo': os.path.join(datasets_cache_dir, '5_utr_classification'), 'name': "", 'alias': "utr5_ben_pat", 'len': 1000, 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 2, 'data_alias': "UTR'5 Class."},
    {'taskId': 29,'repo': os.path.join(datasets_cache_dir, '5_utr_classification_fixed_1200'), 'name': "", 'alias': "utr5_ben_pat_fixed", 'len': 1200, 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 2, 'data_alias': "UTR'5 Class. (fixed length)"}
]

MODELS = [
    {'modelId': 1,'repo': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'name': 'nucleotide-transformer-v2-50m-multi-species', 'data_alias': 'NT-MS V2 (50M)' ,'tokenizer': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species"},
    {'modelId': 2,'repo': "InstaDeepAI/nucleotide-transformer-v2-100m-multi-species", 'name': 'nucleotide-transformer-v2-100m-multi-species', 'data_alias': 'NT-MS V2 (100M)' ,'tokenizer': "InstaDeepAI/nucleotide-transformer-v2-100m-multi-species"},
    {'modelId': 3,'repo': "InstaDeepAI/nucleotide-transformer-v2-250m-multi-species", 'name': 'nucleotide-transformer-v2-250m-multi-species', 'data_alias': 'NT-MS V2 (250M)' ,'tokenizer': "InstaDeepAI/nucleotide-transformer-v2-250m-multi-species"},
    {'modelId': 4,'repo': "InstaDeepAI/nucleotide-transformer-v2-500m-multi-species", 'name': 'nucleotide-transformer-v2-500m-multi-species', 'data_alias': 'NT-MS V2 (500M)' ,'tokenizer': "InstaDeepAI/nucleotide-transformer-v2-500m-multi-species"},
    {'modelId': 5,'repo': "InstaDeepAI/nucleotide-transformer-500m-1000g", 'name': 'nucleotide-transformer-500m-1000g', 'data_alias': 'NT-1000g (500M)' ,'tokenizer': "InstaDeepAI/nucleotide-transformer-500m-1000g"},
    {'modelId': 6,'repo': "InstaDeepAI/nucleotide-transformer-500m-human-ref", 'name': 'nucleotide-transformer-500m-human-ref', 'data_alias': 'NT-Human-Ref. (500M)' ,'tokenizer': "InstaDeepAI/nucleotide-transformer-500m-human-ref"}
]

PRETRAINED_MODELS = [
    {'modelId': 0,'repo': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'name': 'nucleotide-transformer-v2-50m-multi-species', 'data_alias': 'NT-MS V2 (50M)' ,'tokenizer': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'checkpoint': ''},
    {'modelId': 1,'repo': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'name': 'nucleotide-transformer-v2-50m-multi-species-overlap-sh-1-35-1-8-gc-0-4-0-6-6B', 'data_alias': 'NT-MS V2 (50M) (Overlapping, Shannon 1.35-1.8, GC 0.4-0.6, 6B)' ,'tokenizer': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'checkpoint': 'overlap_multi_genome_dataset_sh_gc/checkpoint-6000/'},
    {'modelId': 2,'repo': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'name': 'nucleotide-transformer-v2-50m-multi-species-overlap-sh-1-35-1-8-gc-0-4-0-6-12B', 'data_alias': 'NT-MS V2 (50M) (Overlapping, Shannon 1.35-1.8, GC 0.4-0.6, 12B)' ,'tokenizer': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'checkpoint': 'overlap_multi_genome_dataset_sh_gc/checkpoint-12000/'},
    {'modelId': 3,'repo': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'name': 'nucleotide-transformer-v2-50m-multi-species-sh-1-35-1-8-gc-0-4-0-6-6B', 'data_alias': 'NT-MS V2 (50M) (Shannon 1.35-1.8, GC 0.4-0.6, 6B)' ,'tokenizer': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'checkpoint': 'default_multi_genome_dataset_sh_gc/checkpoint-6000/'},
    {'modelId': 4,'repo': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'name': 'nucleotide-transformer-v2-50m-multi-species-sh-1-35-1-8-gc-0-4-0-6-12B', 'data_alias': 'NT-MS V2 (50M) (Shannon 1.35-1.8, GC 0.4-0.6, 12B)' ,'tokenizer': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'checkpoint': 'default_multi_genome_dataset_sh_gc/checkpoint-12000/'},
    {'modelId': 5,'repo': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'name': 'nucleotide-transformer-v2-50m-multi-species-overlap-6B', 'data_alias': 'NT-MS V2 (50M) (Overlapping, 6B)' ,'tokenizer': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'checkpoint': 'overlap_multi_genome_dataset/checkpoint-6000/'},
    {'modelId': 6,'repo': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'name': 'nucleotide-transformer-v2-50m-multi-species-overlap-12B', 'data_alias': 'NT-MS V2 (50M) (Overlapping, 12B)' ,'tokenizer': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'checkpoint': 'overlap_multi_genome_dataset/checkpoint-12000/'},
    {'modelId': 7,'repo': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'name': 'nucleotide-transformer-v2-50m-multi-species-6B', 'data_alias': 'NT-MS V2 (50M) (6B)' ,'tokenizer': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'checkpoint': 'default_multi_genome_dataset/checkpoint-6000/'},
    {'modelId': 8,'repo': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'name': 'nucleotide-transformer-v2-50m-multi-species-12B', 'data_alias': 'NT-MS V2 (50M) (12B)' ,'tokenizer': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'checkpoint': 'default_multi_genome_dataset/checkpoint-12000/'},
    {'modelId': 9,'repo': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'name': 'nucleotide-transformer-v2-50m-multi-species-overlap-sh-1-35-1-8-gc-0-4-0-6-6B', 'data_alias': 'NT-MS V2 (50M) (2kb, Overlapping, Shannon 1.35-1.8, GC 0.4-0.6, 6B)' ,'tokenizer': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'checkpoint': 'overlap_multi_genome_dataset_sh_gc/checkpoint-6000/'},
    {'modelId': 10,'repo': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'name': 'nucleotide-transformer-v2-50m-multi-species-overlap-sh-1-35-1-8-gc-0-4-0-6-12B', 'data_alias': 'NT-MS V2 (50M) (2kb, Overlapping, Shannon 1.35-1.8, GC 0.4-0.6, 12B)' ,'tokenizer': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'checkpoint': 'overlap_multi_genome_dataset_sh_gc/checkpoint-12000/'},
    {'modelId': 11,'repo': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'name': 'nucleotide-transformer-v2-50m-multi-species-sh-1-35-1-8-gc-0-4-0-6-6B', 'data_alias': 'NT-MS V2 (50M) (2kb, Shannon 1.35-1.8, GC 0.4-0.6, 6B)' ,'tokenizer': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'checkpoint': 'default_multi_genome_dataset_sh_gc/checkpoint-6000/'},
    {'modelId': 12,'repo': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'name': 'nucleotide-transformer-v2-50m-multi-species-sh-1-35-1-8-gc-0-4-0-6-12B', 'data_alias': 'NT-MS V2 (50M) (2kb, Shannon 1.35-1.8, GC 0.4-0.6, 12B)' ,'tokenizer': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'checkpoint': 'default_multi_genome_dataset_sh_gc/checkpoint-12000/'},
    {'modelId': 13,'repo': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'name': 'nucleotide-transformer-v2-50m-multi-species-overlap-6B', 'data_alias': 'NT-MS V2 (50M) (2kb, Overlapping, 6B)' ,'tokenizer': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'checkpoint': 'overlap_multi_genome_dataset/checkpoint-6000/'},
    {'modelId': 14,'repo': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'name': 'nucleotide-transformer-v2-50m-multi-species-overlap-12B', 'data_alias': 'NT-MS V2 (50M) (2kb, Overlapping, 12B)' ,'tokenizer': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'checkpoint': 'overlap_multi_genome_dataset/checkpoint-12000/'},
    {'modelId': 15,'repo': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'name': 'nucleotide-transformer-v2-50m-multi-species-6B', 'data_alias': 'NT-MS V2 (50M) (2kb, 6B)' ,'tokenizer': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'checkpoint': 'default_multi_genome_dataset/checkpoint-6000/'},
    {'modelId': 16,'repo': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'name': 'nucleotide-transformer-v2-50m-multi-species-12B', 'data_alias': 'NT-MS V2 (50M) (2kb, 12B)' ,'tokenizer': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'checkpoint': 'default_multi_genome_dataset/checkpoint-12000/'},
    {'modelId': 17,'repo': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'name': 'ntv2-pca-multi-species-12B', 'data_alias': 'NT-MS V2 (50M) (1kb, PCA-Embed, 12B)' ,'tokenizer': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species", 'checkpoint': 'pca_embed_multi_species/checkpoint-12000/'},
    {'modelId': 18, 'repo': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species",
     'name': 'ntv2-logan-ewc-0_5', 'data_alias': 'NT-MS V2 (50M) (1kb, Logan, EWC-Lambda 0.5, 12B)',
     'tokenizer': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species",
     'checkpoint': 'overlap_logan_ewc_0_5/checkpoint-12000/'},
    {'modelId': 19, 'repo': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species",
         'name': 'ntv2-logan-ewc-1', 'data_alias': 'NT-MS V2 (50M) (1kb, Logan, EWC-Lambda 1, 12B)',
         'tokenizer': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species",
         'checkpoint': 'overlap_logan_ewc_1/checkpoint-12000/'},
    {'modelId': 20, 'repo': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species",
         'name': 'ntv2-logan-ewc-2', 'data_alias': 'NT-MS V2 (50M) (1kb, Logan, EWC-Lambda 2, 12B)',
         'tokenizer': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species",
         'checkpoint': 'overlap_logan_ewc_2/checkpoint-12000/'},
    {'modelId': 21, 'repo': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species",
         'name': 'ntv2-logan-ewc-5', 'data_alias': 'NT-MS V2 (50M) (1kb, Logan, EWC-Lambda 5, 12B)',
         'tokenizer': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species",
         'checkpoint': 'overlap_logan_ewc_5/checkpoint-12000/'},
    {'modelId': 22, 'repo': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species",
         'name': 'ntv2-logan-ewc-10', 'data_alias': 'NT-MS V2 (50M) (1kb, Logan, EWC-Lambda 10, 12B)',
         'tokenizer': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species",
         'checkpoint': 'overlap_logan_ewc_10/checkpoint-12000/'},
    {'modelId': 23, 'repo': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species",
         'name': 'ntv2-logan-ewc-25', 'data_alias': 'NT-MS V2 (50M) (1kb, Logan, EWC-Lambda 25, 12B)',
         'tokenizer': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species",
         'checkpoint': 'overlap_logan_ewc_25/checkpoint-12000/'},
    {'modelId': 24, 'repo': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species",
             'name': 'ntv2-ms-pca-256', 'data_alias': 'NT-MS V2 (50M) (1kb, PCA, 12B)',
             'tokenizer': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species",
             'checkpoint': 'pca_256_multi_species_overlap/checkpoint-12000/'},
    {'modelId': 25, 'repo': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species",
                 'name': 'ntv2-ms-pca-256', 'data_alias': 'NT-MS V2 (50M) (1kb, PCA, 12B)',
                 'tokenizer': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species",
                 'checkpoint': 'pca_mean_256_multi_species_overlap/checkpoint-12000/'},
    {'modelId': 26, 'repo': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species",
                 'name': 'ntv2-ms-pca-256', 'data_alias': 'NT-MS V2 (50M) (1kb, PCA, 12B)',
                 'tokenizer': "InstaDeepAI/nucleotide-transformer-v2-50m-multi-species",
                 'checkpoint': 'pca_cls_256_multi_species_overlap/checkpoint-12000/'},
]