#!/bin/bash

sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-random-weights-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-100m-multi-species-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-250m-multi-species-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-random-weights-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-1000g-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-human-ref-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl-lora.sh