#!/bin/bash

sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-promoter_all-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-promoter_tata-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-promoter_no_tata-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-enhancers-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-enhancers_types-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-splice_sites_all-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-splice_sites_acceptors-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-splice_sites_donors-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-H2AFZ-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-H3K27ac-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-H3K27me3-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-H3K36me3-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-H3K4me1-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-H3K4me2-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-H3K4me3-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-H3K9ac-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-H3K9me3-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-H4K20me1-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-Genomic_Benchmarks_human_ensembl_regulatory-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-Genomic_Benchmarks_demo_human_or_worm-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-Genomic_Benchmarks_human_ocr_ensembl-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-Genomic_Benchmarks_drosophila_enhancers_stark-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-Genomic_Benchmarks_demo_coding_vs_intergenomic_seqs-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-Genomic_Benchmarks_human_enhancers_ensembl-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-Genomic_Benchmarks_human_enhancers_cohn-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-Genomic_Benchmarks_human_nontata_promoters-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-random-weights-promoter_all-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-random-weights-promoter_tata-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-random-weights-promoter_no_tata-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-random-weights-enhancers-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-random-weights-enhancers_types-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-random-weights-splice_sites_all-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-random-weights-splice_sites_acceptors-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-random-weights-splice_sites_donors-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-random-weights-H2AFZ-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-random-weights-H3K27ac-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-random-weights-H3K27me3-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-random-weights-H3K36me3-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-random-weights-H3K4me1-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-random-weights-H3K4me2-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-random-weights-H3K4me3-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-random-weights-H3K9ac-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-random-weights-H3K9me3-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-random-weights-H4K20me1-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-random-weights-Genomic_Benchmarks_human_ensembl_regulatory-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-random-weights-Genomic_Benchmarks_demo_human_or_worm-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-random-weights-Genomic_Benchmarks_human_ocr_ensembl-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-random-weights-Genomic_Benchmarks_drosophila_enhancers_stark-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-random-weights-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-random-weights-Genomic_Benchmarks_demo_coding_vs_intergenomic_seqs-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-random-weights-Genomic_Benchmarks_human_enhancers_ensembl-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-random-weights-Genomic_Benchmarks_human_enhancers_cohn-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-random-weights-Genomic_Benchmarks_human_nontata_promoters-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-100m-multi-species-promoter_all-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-100m-multi-species-promoter_tata-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-100m-multi-species-promoter_no_tata-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-100m-multi-species-enhancers-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-100m-multi-species-enhancers_types-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-100m-multi-species-splice_sites_all-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-100m-multi-species-splice_sites_acceptors-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-100m-multi-species-splice_sites_donors-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-100m-multi-species-H2AFZ-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-100m-multi-species-H3K27ac-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-100m-multi-species-H3K27me3-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-100m-multi-species-H3K36me3-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-100m-multi-species-H3K4me1-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-100m-multi-species-H3K4me2-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-100m-multi-species-H3K4me3-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-100m-multi-species-H3K9ac-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-100m-multi-species-H3K9me3-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-100m-multi-species-H4K20me1-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-100m-multi-species-Genomic_Benchmarks_human_ensembl_regulatory-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-100m-multi-species-Genomic_Benchmarks_demo_human_or_worm-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-100m-multi-species-Genomic_Benchmarks_human_ocr_ensembl-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-100m-multi-species-Genomic_Benchmarks_drosophila_enhancers_stark-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-100m-multi-species-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-100m-multi-species-Genomic_Benchmarks_demo_coding_vs_intergenomic_seqs-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-100m-multi-species-Genomic_Benchmarks_human_enhancers_ensembl-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-100m-multi-species-Genomic_Benchmarks_human_enhancers_cohn-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-100m-multi-species-Genomic_Benchmarks_human_nontata_promoters-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-250m-multi-species-promoter_all-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-250m-multi-species-promoter_tata-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-250m-multi-species-promoter_no_tata-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-250m-multi-species-enhancers-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-250m-multi-species-enhancers_types-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-250m-multi-species-splice_sites_all-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-250m-multi-species-splice_sites_acceptors-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-250m-multi-species-splice_sites_donors-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-250m-multi-species-H2AFZ-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-250m-multi-species-H3K27ac-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-250m-multi-species-H3K27me3-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-250m-multi-species-H3K36me3-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-250m-multi-species-H3K4me1-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-250m-multi-species-H3K4me2-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-250m-multi-species-H3K4me3-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-250m-multi-species-H3K9ac-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-250m-multi-species-H3K9me3-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-250m-multi-species-H4K20me1-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-250m-multi-species-Genomic_Benchmarks_human_ensembl_regulatory-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-250m-multi-species-Genomic_Benchmarks_demo_human_or_worm-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-250m-multi-species-Genomic_Benchmarks_human_ocr_ensembl-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-250m-multi-species-Genomic_Benchmarks_drosophila_enhancers_stark-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-250m-multi-species-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-250m-multi-species-Genomic_Benchmarks_demo_coding_vs_intergenomic_seqs-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-250m-multi-species-Genomic_Benchmarks_human_enhancers_ensembl-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-250m-multi-species-Genomic_Benchmarks_human_enhancers_cohn-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-250m-multi-species-Genomic_Benchmarks_human_nontata_promoters-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-promoter_all-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-promoter_tata-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-promoter_no_tata-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-enhancers-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-enhancers_types-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-splice_sites_all-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-splice_sites_acceptors-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-splice_sites_donors-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-H2AFZ-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-H3K27ac-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-H3K27me3-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-H3K36me3-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-H3K4me1-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-H3K4me2-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-H3K4me3-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-H3K9ac-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-H3K9me3-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-H4K20me1-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-Genomic_Benchmarks_human_ensembl_regulatory-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-Genomic_Benchmarks_demo_human_or_worm-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-Genomic_Benchmarks_human_ocr_ensembl-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-Genomic_Benchmarks_drosophila_enhancers_stark-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-Genomic_Benchmarks_demo_coding_vs_intergenomic_seqs-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-Genomic_Benchmarks_human_enhancers_ensembl-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-Genomic_Benchmarks_human_enhancers_cohn-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-Genomic_Benchmarks_human_nontata_promoters-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-random-weights-promoter_all-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-random-weights-promoter_tata-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-random-weights-promoter_no_tata-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-random-weights-enhancers-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-random-weights-enhancers_types-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-random-weights-splice_sites_all-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-random-weights-splice_sites_acceptors-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-random-weights-splice_sites_donors-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-random-weights-H2AFZ-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-random-weights-H3K27ac-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-random-weights-H3K27me3-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-random-weights-H3K36me3-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-random-weights-H3K4me1-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-random-weights-H3K4me2-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-random-weights-H3K4me3-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-random-weights-H3K9ac-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-random-weights-H3K9me3-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-random-weights-H4K20me1-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-random-weights-Genomic_Benchmarks_human_ensembl_regulatory-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-random-weights-Genomic_Benchmarks_demo_human_or_worm-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-random-weights-Genomic_Benchmarks_human_ocr_ensembl-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-random-weights-Genomic_Benchmarks_drosophila_enhancers_stark-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-random-weights-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-random-weights-Genomic_Benchmarks_demo_coding_vs_intergenomic_seqs-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-random-weights-Genomic_Benchmarks_human_enhancers_ensembl-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-random-weights-Genomic_Benchmarks_human_enhancers_cohn-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-500m-multi-species-random-weights-Genomic_Benchmarks_human_nontata_promoters-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-1000g-promoter_all-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-1000g-promoter_tata-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-1000g-promoter_no_tata-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-1000g-enhancers-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-1000g-enhancers_types-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-1000g-splice_sites_all-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-1000g-splice_sites_acceptors-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-1000g-splice_sites_donors-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-1000g-H2AFZ-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-1000g-H3K27ac-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-1000g-H3K27me3-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-1000g-H3K36me3-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-1000g-H3K4me1-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-1000g-H3K4me2-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-1000g-H3K4me3-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-1000g-H3K9ac-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-1000g-H3K9me3-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-1000g-H4K20me1-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-1000g-Genomic_Benchmarks_human_ensembl_regulatory-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-1000g-Genomic_Benchmarks_demo_human_or_worm-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-1000g-Genomic_Benchmarks_human_ocr_ensembl-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-1000g-Genomic_Benchmarks_drosophila_enhancers_stark-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-1000g-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-1000g-Genomic_Benchmarks_demo_coding_vs_intergenomic_seqs-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-1000g-Genomic_Benchmarks_human_enhancers_ensembl-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-1000g-Genomic_Benchmarks_human_enhancers_cohn-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-1000g-Genomic_Benchmarks_human_nontata_promoters-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-human-ref-promoter_all-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-human-ref-promoter_tata-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-human-ref-promoter_no_tata-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-human-ref-enhancers-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-human-ref-enhancers_types-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-human-ref-splice_sites_all-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-human-ref-splice_sites_acceptors-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-human-ref-splice_sites_donors-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-human-ref-H2AFZ-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-human-ref-H3K27ac-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-human-ref-H3K27me3-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-human-ref-H3K36me3-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-human-ref-H3K4me1-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-human-ref-H3K4me2-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-human-ref-H3K4me3-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-human-ref-H3K9ac-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-human-ref-H3K9me3-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-human-ref-H4K20me1-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-human-ref-Genomic_Benchmarks_human_ensembl_regulatory-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-human-ref-Genomic_Benchmarks_demo_human_or_worm-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-human-ref-Genomic_Benchmarks_human_ocr_ensembl-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-human-ref-Genomic_Benchmarks_drosophila_enhancers_stark-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-human-ref-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-human-ref-Genomic_Benchmarks_demo_coding_vs_intergenomic_seqs-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-human-ref-Genomic_Benchmarks_human_enhancers_ensembl-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-human-ref-Genomic_Benchmarks_human_enhancers_cohn-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-500m-human-ref-Genomic_Benchmarks_human_nontata_promoters-lora.sh
