#!/bin/bash

sbatch nucleotide-transformer-v2-50m-multi-species-promoter_all-lora
sbatch nucleotide-transformer-v2-50m-multi-species-promoter_tata-lora
sbatch nucleotide-transformer-v2-50m-multi-species-promoter_no_tata-lora
sbatch nucleotide-transformer-v2-50m-multi-species-enhancers-lora
sbatch nucleotide-transformer-v2-50m-multi-species-enhancers_types-lora
sbatch nucleotide-transformer-v2-50m-multi-species-splice_sites_all-lora
sbatch nucleotide-transformer-v2-50m-multi-species-splice_sites_acceptors-lora
sbatch nucleotide-transformer-v2-50m-multi-species-splice_sites_donors-lora
sbatch nucleotide-transformer-v2-50m-multi-species-H2AFZ-lora
sbatch nucleotide-transformer-v2-50m-multi-species-H3K27ac-lora
sbatch nucleotide-transformer-v2-50m-multi-species-H3K27me3-lora
sbatch nucleotide-transformer-v2-50m-multi-species-H3K36me3-lora
sbatch nucleotide-transformer-v2-50m-multi-species-H3K4me1-lora
sbatch nucleotide-transformer-v2-50m-multi-species-H3K4me2-lora
sbatch nucleotide-transformer-v2-50m-multi-species-H3K4me3-lora
sbatch nucleotide-transformer-v2-50m-multi-species-H3K9ac-lora
sbatch nucleotide-transformer-v2-50m-multi-species-H3K9me3-lora
sbatch nucleotide-transformer-v2-50m-multi-species-H4K20me1-lora
sbatch nucleotide-transformer-v2-50m-multi-species-Genomic_Benchmarks_human_ensembl_regulatory-lora
sbatch nucleotide-transformer-v2-50m-multi-species-Genomic_Benchmarks_demo_human_or_worm-lora
sbatch nucleotide-transformer-v2-50m-multi-species-Genomic_Benchmarks_human_ocr_ensembl-lora
sbatch nucleotide-transformer-v2-50m-multi-species-Genomic_Benchmarks_drosophila_enhancers_stark-lora
sbatch nucleotide-transformer-v2-50m-multi-species-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl-lora
sbatch nucleotide-transformer-v2-50m-multi-species-Genomic_Benchmarks_demo_coding_vs_intergenomic_seqs-lora
sbatch nucleotide-transformer-v2-50m-multi-species-Genomic_Benchmarks_human_enhancers_ensembl-lora
sbatch nucleotide-transformer-v2-50m-multi-species-Genomic_Benchmarks_human_enhancers_cohn-lora
sbatch nucleotide-transformer-v2-50m-multi-species-Genomic_Benchmarks_human_nontata_promoters-lora
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-promoter_all-lora
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-promoter_tata-lora
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-promoter_no_tata-lora
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-enhancers-lora
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-enhancers_types-lora
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-splice_sites_all-lora
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-splice_sites_acceptors-lora
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-splice_sites_donors-lora
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-H2AFZ-lora
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-H3K27ac-lora
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-H3K27me3-lora
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-H3K36me3-lora
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-H3K4me1-lora
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-H3K4me2-lora
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-H3K4me3-lora
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-H3K9ac-lora
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-H3K9me3-lora
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-H4K20me1-lora
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-Genomic_Benchmarks_human_ensembl_regulatory-lora
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-Genomic_Benchmarks_demo_human_or_worm-lora
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-Genomic_Benchmarks_human_ocr_ensembl-lora
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-Genomic_Benchmarks_drosophila_enhancers_stark-lora
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl-lora
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-Genomic_Benchmarks_demo_coding_vs_intergenomic_seqs-lora
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-Genomic_Benchmarks_human_enhancers_ensembl-lora
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-Genomic_Benchmarks_human_enhancers_cohn-lora
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-Genomic_Benchmarks_human_nontata_promoters-lora
sbatch nucleotide-transformer-v2-100m-multi-species-promoter_all-lora
sbatch nucleotide-transformer-v2-100m-multi-species-promoter_tata-lora
sbatch nucleotide-transformer-v2-100m-multi-species-promoter_no_tata-lora
sbatch nucleotide-transformer-v2-100m-multi-species-enhancers-lora
sbatch nucleotide-transformer-v2-100m-multi-species-enhancers_types-lora
sbatch nucleotide-transformer-v2-100m-multi-species-splice_sites_all-lora
sbatch nucleotide-transformer-v2-100m-multi-species-splice_sites_acceptors-lora
sbatch nucleotide-transformer-v2-100m-multi-species-splice_sites_donors-lora
sbatch nucleotide-transformer-v2-100m-multi-species-H2AFZ-lora
sbatch nucleotide-transformer-v2-100m-multi-species-H3K27ac-lora
sbatch nucleotide-transformer-v2-100m-multi-species-H3K27me3-lora
sbatch nucleotide-transformer-v2-100m-multi-species-H3K36me3-lora
sbatch nucleotide-transformer-v2-100m-multi-species-H3K4me1-lora
sbatch nucleotide-transformer-v2-100m-multi-species-H3K4me2-lora
sbatch nucleotide-transformer-v2-100m-multi-species-H3K4me3-lora
sbatch nucleotide-transformer-v2-100m-multi-species-H3K9ac-lora
sbatch nucleotide-transformer-v2-100m-multi-species-H3K9me3-lora
sbatch nucleotide-transformer-v2-100m-multi-species-H4K20me1-lora
sbatch nucleotide-transformer-v2-100m-multi-species-Genomic_Benchmarks_human_ensembl_regulatory-lora
sbatch nucleotide-transformer-v2-100m-multi-species-Genomic_Benchmarks_demo_human_or_worm-lora
sbatch nucleotide-transformer-v2-100m-multi-species-Genomic_Benchmarks_human_ocr_ensembl-lora
sbatch nucleotide-transformer-v2-100m-multi-species-Genomic_Benchmarks_drosophila_enhancers_stark-lora
sbatch nucleotide-transformer-v2-100m-multi-species-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl-lora
sbatch nucleotide-transformer-v2-100m-multi-species-Genomic_Benchmarks_demo_coding_vs_intergenomic_seqs-lora
sbatch nucleotide-transformer-v2-100m-multi-species-Genomic_Benchmarks_human_enhancers_ensembl-lora
sbatch nucleotide-transformer-v2-100m-multi-species-Genomic_Benchmarks_human_enhancers_cohn-lora
sbatch nucleotide-transformer-v2-100m-multi-species-Genomic_Benchmarks_human_nontata_promoters-lora
sbatch nucleotide-transformer-v2-250m-multi-species-promoter_all-lora
sbatch nucleotide-transformer-v2-250m-multi-species-promoter_tata-lora
sbatch nucleotide-transformer-v2-250m-multi-species-promoter_no_tata-lora
sbatch nucleotide-transformer-v2-250m-multi-species-enhancers-lora
sbatch nucleotide-transformer-v2-250m-multi-species-enhancers_types-lora
sbatch nucleotide-transformer-v2-250m-multi-species-splice_sites_all-lora
sbatch nucleotide-transformer-v2-250m-multi-species-splice_sites_acceptors-lora
sbatch nucleotide-transformer-v2-250m-multi-species-splice_sites_donors-lora
sbatch nucleotide-transformer-v2-250m-multi-species-H2AFZ-lora
sbatch nucleotide-transformer-v2-250m-multi-species-H3K27ac-lora
sbatch nucleotide-transformer-v2-250m-multi-species-H3K27me3-lora
sbatch nucleotide-transformer-v2-250m-multi-species-H3K36me3-lora
sbatch nucleotide-transformer-v2-250m-multi-species-H3K4me1-lora
sbatch nucleotide-transformer-v2-250m-multi-species-H3K4me2-lora
sbatch nucleotide-transformer-v2-250m-multi-species-H3K4me3-lora
sbatch nucleotide-transformer-v2-250m-multi-species-H3K9ac-lora
sbatch nucleotide-transformer-v2-250m-multi-species-H3K9me3-lora
sbatch nucleotide-transformer-v2-250m-multi-species-H4K20me1-lora
sbatch nucleotide-transformer-v2-250m-multi-species-Genomic_Benchmarks_human_ensembl_regulatory-lora
sbatch nucleotide-transformer-v2-250m-multi-species-Genomic_Benchmarks_demo_human_or_worm-lora
sbatch nucleotide-transformer-v2-250m-multi-species-Genomic_Benchmarks_human_ocr_ensembl-lora
sbatch nucleotide-transformer-v2-250m-multi-species-Genomic_Benchmarks_drosophila_enhancers_stark-lora
sbatch nucleotide-transformer-v2-250m-multi-species-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl-lora
sbatch nucleotide-transformer-v2-250m-multi-species-Genomic_Benchmarks_demo_coding_vs_intergenomic_seqs-lora
sbatch nucleotide-transformer-v2-250m-multi-species-Genomic_Benchmarks_human_enhancers_ensembl-lora
sbatch nucleotide-transformer-v2-250m-multi-species-Genomic_Benchmarks_human_enhancers_cohn-lora
sbatch nucleotide-transformer-v2-250m-multi-species-Genomic_Benchmarks_human_nontata_promoters-lora
sbatch nucleotide-transformer-v2-500m-multi-species-promoter_all-lora
sbatch nucleotide-transformer-v2-500m-multi-species-promoter_tata-lora
sbatch nucleotide-transformer-v2-500m-multi-species-promoter_no_tata-lora
sbatch nucleotide-transformer-v2-500m-multi-species-enhancers-lora
sbatch nucleotide-transformer-v2-500m-multi-species-enhancers_types-lora
sbatch nucleotide-transformer-v2-500m-multi-species-splice_sites_all-lora
sbatch nucleotide-transformer-v2-500m-multi-species-splice_sites_acceptors-lora
sbatch nucleotide-transformer-v2-500m-multi-species-splice_sites_donors-lora
sbatch nucleotide-transformer-v2-500m-multi-species-H2AFZ-lora
sbatch nucleotide-transformer-v2-500m-multi-species-H3K27ac-lora
sbatch nucleotide-transformer-v2-500m-multi-species-H3K27me3-lora
sbatch nucleotide-transformer-v2-500m-multi-species-H3K36me3-lora
sbatch nucleotide-transformer-v2-500m-multi-species-H3K4me1-lora
sbatch nucleotide-transformer-v2-500m-multi-species-H3K4me2-lora
sbatch nucleotide-transformer-v2-500m-multi-species-H3K4me3-lora
sbatch nucleotide-transformer-v2-500m-multi-species-H3K9ac-lora
sbatch nucleotide-transformer-v2-500m-multi-species-H3K9me3-lora
sbatch nucleotide-transformer-v2-500m-multi-species-H4K20me1-lora
sbatch nucleotide-transformer-v2-500m-multi-species-Genomic_Benchmarks_human_ensembl_regulatory-lora
sbatch nucleotide-transformer-v2-500m-multi-species-Genomic_Benchmarks_demo_human_or_worm-lora
sbatch nucleotide-transformer-v2-500m-multi-species-Genomic_Benchmarks_human_ocr_ensembl-lora
sbatch nucleotide-transformer-v2-500m-multi-species-Genomic_Benchmarks_drosophila_enhancers_stark-lora
sbatch nucleotide-transformer-v2-500m-multi-species-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl-lora
sbatch nucleotide-transformer-v2-500m-multi-species-Genomic_Benchmarks_demo_coding_vs_intergenomic_seqs-lora
sbatch nucleotide-transformer-v2-500m-multi-species-Genomic_Benchmarks_human_enhancers_ensembl-lora
sbatch nucleotide-transformer-v2-500m-multi-species-Genomic_Benchmarks_human_enhancers_cohn-lora
sbatch nucleotide-transformer-v2-500m-multi-species-Genomic_Benchmarks_human_nontata_promoters-lora
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-promoter_all-lora
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-promoter_tata-lora
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-promoter_no_tata-lora
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-enhancers-lora
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-enhancers_types-lora
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-splice_sites_all-lora
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-splice_sites_acceptors-lora
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-splice_sites_donors-lora
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-H2AFZ-lora
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-H3K27ac-lora
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-H3K27me3-lora
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-H3K36me3-lora
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-H3K4me1-lora
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-H3K4me2-lora
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-H3K4me3-lora
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-H3K9ac-lora
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-H3K9me3-lora
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-H4K20me1-lora
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-Genomic_Benchmarks_human_ensembl_regulatory-lora
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-Genomic_Benchmarks_demo_human_or_worm-lora
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-Genomic_Benchmarks_human_ocr_ensembl-lora
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-Genomic_Benchmarks_drosophila_enhancers_stark-lora
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl-lora
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-Genomic_Benchmarks_demo_coding_vs_intergenomic_seqs-lora
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-Genomic_Benchmarks_human_enhancers_ensembl-lora
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-Genomic_Benchmarks_human_enhancers_cohn-lora
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-Genomic_Benchmarks_human_nontata_promoters-lora
sbatch nucleotide-transformer-500m-1000g-promoter_all-lora
sbatch nucleotide-transformer-500m-1000g-promoter_tata-lora
sbatch nucleotide-transformer-500m-1000g-promoter_no_tata-lora
sbatch nucleotide-transformer-500m-1000g-enhancers-lora
sbatch nucleotide-transformer-500m-1000g-enhancers_types-lora
sbatch nucleotide-transformer-500m-1000g-splice_sites_all-lora
sbatch nucleotide-transformer-500m-1000g-splice_sites_acceptors-lora
sbatch nucleotide-transformer-500m-1000g-splice_sites_donors-lora
sbatch nucleotide-transformer-500m-1000g-H2AFZ-lora
sbatch nucleotide-transformer-500m-1000g-H3K27ac-lora
sbatch nucleotide-transformer-500m-1000g-H3K27me3-lora
sbatch nucleotide-transformer-500m-1000g-H3K36me3-lora
sbatch nucleotide-transformer-500m-1000g-H3K4me1-lora
sbatch nucleotide-transformer-500m-1000g-H3K4me2-lora
sbatch nucleotide-transformer-500m-1000g-H3K4me3-lora
sbatch nucleotide-transformer-500m-1000g-H3K9ac-lora
sbatch nucleotide-transformer-500m-1000g-H3K9me3-lora
sbatch nucleotide-transformer-500m-1000g-H4K20me1-lora
sbatch nucleotide-transformer-500m-1000g-Genomic_Benchmarks_human_ensembl_regulatory-lora
sbatch nucleotide-transformer-500m-1000g-Genomic_Benchmarks_demo_human_or_worm-lora
sbatch nucleotide-transformer-500m-1000g-Genomic_Benchmarks_human_ocr_ensembl-lora
sbatch nucleotide-transformer-500m-1000g-Genomic_Benchmarks_drosophila_enhancers_stark-lora
sbatch nucleotide-transformer-500m-1000g-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl-lora
sbatch nucleotide-transformer-500m-1000g-Genomic_Benchmarks_demo_coding_vs_intergenomic_seqs-lora
sbatch nucleotide-transformer-500m-1000g-Genomic_Benchmarks_human_enhancers_ensembl-lora
sbatch nucleotide-transformer-500m-1000g-Genomic_Benchmarks_human_enhancers_cohn-lora
sbatch nucleotide-transformer-500m-1000g-Genomic_Benchmarks_human_nontata_promoters-lora
sbatch nucleotide-transformer-500m-human-ref-promoter_all-lora
sbatch nucleotide-transformer-500m-human-ref-promoter_tata-lora
sbatch nucleotide-transformer-500m-human-ref-promoter_no_tata-lora
sbatch nucleotide-transformer-500m-human-ref-enhancers-lora
sbatch nucleotide-transformer-500m-human-ref-enhancers_types-lora
sbatch nucleotide-transformer-500m-human-ref-splice_sites_all-lora
sbatch nucleotide-transformer-500m-human-ref-splice_sites_acceptors-lora
sbatch nucleotide-transformer-500m-human-ref-splice_sites_donors-lora
sbatch nucleotide-transformer-500m-human-ref-H2AFZ-lora
sbatch nucleotide-transformer-500m-human-ref-H3K27ac-lora
sbatch nucleotide-transformer-500m-human-ref-H3K27me3-lora
sbatch nucleotide-transformer-500m-human-ref-H3K36me3-lora
sbatch nucleotide-transformer-500m-human-ref-H3K4me1-lora
sbatch nucleotide-transformer-500m-human-ref-H3K4me2-lora
sbatch nucleotide-transformer-500m-human-ref-H3K4me3-lora
sbatch nucleotide-transformer-500m-human-ref-H3K9ac-lora
sbatch nucleotide-transformer-500m-human-ref-H3K9me3-lora
sbatch nucleotide-transformer-500m-human-ref-H4K20me1-lora
sbatch nucleotide-transformer-500m-human-ref-Genomic_Benchmarks_human_ensembl_regulatory-lora
sbatch nucleotide-transformer-500m-human-ref-Genomic_Benchmarks_demo_human_or_worm-lora
sbatch nucleotide-transformer-500m-human-ref-Genomic_Benchmarks_human_ocr_ensembl-lora
sbatch nucleotide-transformer-500m-human-ref-Genomic_Benchmarks_drosophila_enhancers_stark-lora
sbatch nucleotide-transformer-500m-human-ref-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl-lora
sbatch nucleotide-transformer-500m-human-ref-Genomic_Benchmarks_demo_coding_vs_intergenomic_seqs-lora
sbatch nucleotide-transformer-500m-human-ref-Genomic_Benchmarks_human_enhancers_ensembl-lora
sbatch nucleotide-transformer-500m-human-ref-Genomic_Benchmarks_human_enhancers_cohn-lora
sbatch nucleotide-transformer-500m-human-ref-Genomic_Benchmarks_human_nontata_promoters-lora
sbatch nucleotide-transformer-v2-50m-multi-species-promoter_all-promoter_all
sbatch nucleotide-transformer-v2-50m-multi-species-promoter_tata-promoter_tata
sbatch nucleotide-transformer-v2-50m-multi-species-promoter_no_tata-promoter_no_tata
sbatch nucleotide-transformer-v2-50m-multi-species-enhancers-enhancers
sbatch nucleotide-transformer-v2-50m-multi-species-enhancers_types-enhancers_types
sbatch nucleotide-transformer-v2-50m-multi-species-splice_sites_all-splice_sites_all
sbatch nucleotide-transformer-v2-50m-multi-species-splice_sites_acceptors-splice_sites_acceptors
sbatch nucleotide-transformer-v2-50m-multi-species-splice_sites_donors-splice_sites_donors
sbatch nucleotide-transformer-v2-50m-multi-species-H2AFZ-H2AFZ
sbatch nucleotide-transformer-v2-50m-multi-species-H3K27ac-H3K27ac
sbatch nucleotide-transformer-v2-50m-multi-species-H3K27me3-H3K27me3
sbatch nucleotide-transformer-v2-50m-multi-species-H3K36me3-H3K36me3
sbatch nucleotide-transformer-v2-50m-multi-species-H3K4me1-H3K4me1
sbatch nucleotide-transformer-v2-50m-multi-species-H3K4me2-H3K4me2
sbatch nucleotide-transformer-v2-50m-multi-species-H3K4me3-H3K4me3
sbatch nucleotide-transformer-v2-50m-multi-species-H3K9ac-H3K9ac
sbatch nucleotide-transformer-v2-50m-multi-species-H3K9me3-H3K9me3
sbatch nucleotide-transformer-v2-50m-multi-species-H4K20me1-H4K20me1
sbatch nucleotide-transformer-v2-50m-multi-species-Genomic_Benchmarks_human_ensembl_regulatory-Genomic_Benchmarks_human_ensembl_regulatory
sbatch nucleotide-transformer-v2-50m-multi-species-Genomic_Benchmarks_demo_human_or_worm-Genomic_Benchmarks_demo_human_or_worm
sbatch nucleotide-transformer-v2-50m-multi-species-Genomic_Benchmarks_human_ocr_ensembl-Genomic_Benchmarks_human_ocr_ensembl
sbatch nucleotide-transformer-v2-50m-multi-species-Genomic_Benchmarks_drosophila_enhancers_stark-Genomic_Benchmarks_drosophila_enhancers_stark
sbatch nucleotide-transformer-v2-50m-multi-species-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl
sbatch nucleotide-transformer-v2-50m-multi-species-Genomic_Benchmarks_demo_coding_vs_intergenomic_seqs-Genomic_Benchmarks_demo_coding_vs_intergenomic_seqs
sbatch nucleotide-transformer-v2-50m-multi-species-Genomic_Benchmarks_human_enhancers_ensembl-Genomic_Benchmarks_human_enhancers_ensembl
sbatch nucleotide-transformer-v2-50m-multi-species-Genomic_Benchmarks_human_enhancers_cohn-Genomic_Benchmarks_human_enhancers_cohn
sbatch nucleotide-transformer-v2-50m-multi-species-Genomic_Benchmarks_human_nontata_promoters-Genomic_Benchmarks_human_nontata_promoters
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-promoter_all
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-promoter_tata
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-promoter_no_tata
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-enhancers
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-enhancers_types
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-splice_sites_all
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-splice_sites_acceptors
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-splice_sites_donors
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-H2AFZ
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-H3K27ac
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-H3K27me3
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-H3K36me3
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-H3K4me1
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-H3K4me2
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-H3K4me3
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-H3K9ac
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-H3K9me3
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-H4K20me1
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-Genomic_Benchmarks_human_ensembl_regulatory
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-Genomic_Benchmarks_demo_human_or_worm
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-Genomic_Benchmarks_human_ocr_ensembl
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-Genomic_Benchmarks_drosophila_enhancers_stark
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-Genomic_Benchmarks_demo_coding_vs_intergenomic_seqs
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-Genomic_Benchmarks_human_enhancers_ensembl
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-Genomic_Benchmarks_human_enhancers_cohn
sbatch nucleotide-transformer-v2-50m-multi-species-random-weights-Genomic_Benchmarks_human_nontata_promoters
sbatch nucleotide-transformer-v2-100m-multi-species-promoter_all-promoter_all
sbatch nucleotide-transformer-v2-100m-multi-species-promoter_tata-promoter_tata
sbatch nucleotide-transformer-v2-100m-multi-species-promoter_no_tata-promoter_no_tata
sbatch nucleotide-transformer-v2-100m-multi-species-enhancers-enhancers
sbatch nucleotide-transformer-v2-100m-multi-species-enhancers_types-enhancers_types
sbatch nucleotide-transformer-v2-100m-multi-species-splice_sites_all-splice_sites_all
sbatch nucleotide-transformer-v2-100m-multi-species-splice_sites_acceptors-splice_sites_acceptors
sbatch nucleotide-transformer-v2-100m-multi-species-splice_sites_donors-splice_sites_donors
sbatch nucleotide-transformer-v2-100m-multi-species-H2AFZ-H2AFZ
sbatch nucleotide-transformer-v2-100m-multi-species-H3K27ac-H3K27ac
sbatch nucleotide-transformer-v2-100m-multi-species-H3K27me3-H3K27me3
sbatch nucleotide-transformer-v2-100m-multi-species-H3K36me3-H3K36me3
sbatch nucleotide-transformer-v2-100m-multi-species-H3K4me1-H3K4me1
sbatch nucleotide-transformer-v2-100m-multi-species-H3K4me2-H3K4me2
sbatch nucleotide-transformer-v2-100m-multi-species-H3K4me3-H3K4me3
sbatch nucleotide-transformer-v2-100m-multi-species-H3K9ac-H3K9ac
sbatch nucleotide-transformer-v2-100m-multi-species-H3K9me3-H3K9me3
sbatch nucleotide-transformer-v2-100m-multi-species-H4K20me1-H4K20me1
sbatch nucleotide-transformer-v2-100m-multi-species-Genomic_Benchmarks_human_ensembl_regulatory-Genomic_Benchmarks_human_ensembl_regulatory
sbatch nucleotide-transformer-v2-100m-multi-species-Genomic_Benchmarks_demo_human_or_worm-Genomic_Benchmarks_demo_human_or_worm
sbatch nucleotide-transformer-v2-100m-multi-species-Genomic_Benchmarks_human_ocr_ensembl-Genomic_Benchmarks_human_ocr_ensembl
sbatch nucleotide-transformer-v2-100m-multi-species-Genomic_Benchmarks_drosophila_enhancers_stark-Genomic_Benchmarks_drosophila_enhancers_stark
sbatch nucleotide-transformer-v2-100m-multi-species-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl
sbatch nucleotide-transformer-v2-100m-multi-species-Genomic_Benchmarks_demo_coding_vs_intergenomic_seqs-Genomic_Benchmarks_demo_coding_vs_intergenomic_seqs
sbatch nucleotide-transformer-v2-100m-multi-species-Genomic_Benchmarks_human_enhancers_ensembl-Genomic_Benchmarks_human_enhancers_ensembl
sbatch nucleotide-transformer-v2-100m-multi-species-Genomic_Benchmarks_human_enhancers_cohn-Genomic_Benchmarks_human_enhancers_cohn
sbatch nucleotide-transformer-v2-100m-multi-species-Genomic_Benchmarks_human_nontata_promoters-Genomic_Benchmarks_human_nontata_promoters
sbatch nucleotide-transformer-v2-250m-multi-species-promoter_all-promoter_all
sbatch nucleotide-transformer-v2-250m-multi-species-promoter_tata-promoter_tata
sbatch nucleotide-transformer-v2-250m-multi-species-promoter_no_tata-promoter_no_tata
sbatch nucleotide-transformer-v2-250m-multi-species-enhancers-enhancers
sbatch nucleotide-transformer-v2-250m-multi-species-enhancers_types-enhancers_types
sbatch nucleotide-transformer-v2-250m-multi-species-splice_sites_all-splice_sites_all
sbatch nucleotide-transformer-v2-250m-multi-species-splice_sites_acceptors-splice_sites_acceptors
sbatch nucleotide-transformer-v2-250m-multi-species-splice_sites_donors-splice_sites_donors
sbatch nucleotide-transformer-v2-250m-multi-species-H2AFZ-H2AFZ
sbatch nucleotide-transformer-v2-250m-multi-species-H3K27ac-H3K27ac
sbatch nucleotide-transformer-v2-250m-multi-species-H3K27me3-H3K27me3
sbatch nucleotide-transformer-v2-250m-multi-species-H3K36me3-H3K36me3
sbatch nucleotide-transformer-v2-250m-multi-species-H3K4me1-H3K4me1
sbatch nucleotide-transformer-v2-250m-multi-species-H3K4me2-H3K4me2
sbatch nucleotide-transformer-v2-250m-multi-species-H3K4me3-H3K4me3
sbatch nucleotide-transformer-v2-250m-multi-species-H3K9ac-H3K9ac
sbatch nucleotide-transformer-v2-250m-multi-species-H3K9me3-H3K9me3
sbatch nucleotide-transformer-v2-250m-multi-species-H4K20me1-H4K20me1
sbatch nucleotide-transformer-v2-250m-multi-species-Genomic_Benchmarks_human_ensembl_regulatory-Genomic_Benchmarks_human_ensembl_regulatory
sbatch nucleotide-transformer-v2-250m-multi-species-Genomic_Benchmarks_demo_human_or_worm-Genomic_Benchmarks_demo_human_or_worm
sbatch nucleotide-transformer-v2-250m-multi-species-Genomic_Benchmarks_human_ocr_ensembl-Genomic_Benchmarks_human_ocr_ensembl
sbatch nucleotide-transformer-v2-250m-multi-species-Genomic_Benchmarks_drosophila_enhancers_stark-Genomic_Benchmarks_drosophila_enhancers_stark
sbatch nucleotide-transformer-v2-250m-multi-species-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl
sbatch nucleotide-transformer-v2-250m-multi-species-Genomic_Benchmarks_demo_coding_vs_intergenomic_seqs-Genomic_Benchmarks_demo_coding_vs_intergenomic_seqs
sbatch nucleotide-transformer-v2-250m-multi-species-Genomic_Benchmarks_human_enhancers_ensembl-Genomic_Benchmarks_human_enhancers_ensembl
sbatch nucleotide-transformer-v2-250m-multi-species-Genomic_Benchmarks_human_enhancers_cohn-Genomic_Benchmarks_human_enhancers_cohn
sbatch nucleotide-transformer-v2-250m-multi-species-Genomic_Benchmarks_human_nontata_promoters-Genomic_Benchmarks_human_nontata_promoters
sbatch nucleotide-transformer-v2-500m-multi-species-promoter_all-promoter_all
sbatch nucleotide-transformer-v2-500m-multi-species-promoter_tata-promoter_tata
sbatch nucleotide-transformer-v2-500m-multi-species-promoter_no_tata-promoter_no_tata
sbatch nucleotide-transformer-v2-500m-multi-species-enhancers-enhancers
sbatch nucleotide-transformer-v2-500m-multi-species-enhancers_types-enhancers_types
sbatch nucleotide-transformer-v2-500m-multi-species-splice_sites_all-splice_sites_all
sbatch nucleotide-transformer-v2-500m-multi-species-splice_sites_acceptors-splice_sites_acceptors
sbatch nucleotide-transformer-v2-500m-multi-species-splice_sites_donors-splice_sites_donors
sbatch nucleotide-transformer-v2-500m-multi-species-H2AFZ-H2AFZ
sbatch nucleotide-transformer-v2-500m-multi-species-H3K27ac-H3K27ac
sbatch nucleotide-transformer-v2-500m-multi-species-H3K27me3-H3K27me3
sbatch nucleotide-transformer-v2-500m-multi-species-H3K36me3-H3K36me3
sbatch nucleotide-transformer-v2-500m-multi-species-H3K4me1-H3K4me1
sbatch nucleotide-transformer-v2-500m-multi-species-H3K4me2-H3K4me2
sbatch nucleotide-transformer-v2-500m-multi-species-H3K4me3-H3K4me3
sbatch nucleotide-transformer-v2-500m-multi-species-H3K9ac-H3K9ac
sbatch nucleotide-transformer-v2-500m-multi-species-H3K9me3-H3K9me3
sbatch nucleotide-transformer-v2-500m-multi-species-H4K20me1-H4K20me1
sbatch nucleotide-transformer-v2-500m-multi-species-Genomic_Benchmarks_human_ensembl_regulatory-Genomic_Benchmarks_human_ensembl_regulatory
sbatch nucleotide-transformer-v2-500m-multi-species-Genomic_Benchmarks_demo_human_or_worm-Genomic_Benchmarks_demo_human_or_worm
sbatch nucleotide-transformer-v2-500m-multi-species-Genomic_Benchmarks_human_ocr_ensembl-Genomic_Benchmarks_human_ocr_ensembl
sbatch nucleotide-transformer-v2-500m-multi-species-Genomic_Benchmarks_drosophila_enhancers_stark-Genomic_Benchmarks_drosophila_enhancers_stark
sbatch nucleotide-transformer-v2-500m-multi-species-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl
sbatch nucleotide-transformer-v2-500m-multi-species-Genomic_Benchmarks_demo_coding_vs_intergenomic_seqs-Genomic_Benchmarks_demo_coding_vs_intergenomic_seqs
sbatch nucleotide-transformer-v2-500m-multi-species-Genomic_Benchmarks_human_enhancers_ensembl-Genomic_Benchmarks_human_enhancers_ensembl
sbatch nucleotide-transformer-v2-500m-multi-species-Genomic_Benchmarks_human_enhancers_cohn-Genomic_Benchmarks_human_enhancers_cohn
sbatch nucleotide-transformer-v2-500m-multi-species-Genomic_Benchmarks_human_nontata_promoters-Genomic_Benchmarks_human_nontata_promoters
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-promoter_all
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-promoter_tata
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-promoter_no_tata
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-enhancers
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-enhancers_types
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-splice_sites_all
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-splice_sites_acceptors
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-splice_sites_donors
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-H2AFZ
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-H3K27ac
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-H3K27me3
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-H3K36me3
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-H3K4me1
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-H3K4me2
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-H3K4me3
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-H3K9ac
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-H3K9me3
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-H4K20me1
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-Genomic_Benchmarks_human_ensembl_regulatory
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-Genomic_Benchmarks_demo_human_or_worm
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-Genomic_Benchmarks_human_ocr_ensembl
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-Genomic_Benchmarks_drosophila_enhancers_stark
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-Genomic_Benchmarks_demo_coding_vs_intergenomic_seqs
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-Genomic_Benchmarks_human_enhancers_ensembl
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-Genomic_Benchmarks_human_enhancers_cohn
sbatch nucleotide-transformer-v2-500m-multi-species-random-weights-Genomic_Benchmarks_human_nontata_promoters
sbatch nucleotide-transformer-500m-1000g-promoter_all-promoter_all
sbatch nucleotide-transformer-500m-1000g-promoter_tata-promoter_tata
sbatch nucleotide-transformer-500m-1000g-promoter_no_tata-promoter_no_tata
sbatch nucleotide-transformer-500m-1000g-enhancers-enhancers
sbatch nucleotide-transformer-500m-1000g-enhancers_types-enhancers_types
sbatch nucleotide-transformer-500m-1000g-splice_sites_all-splice_sites_all
sbatch nucleotide-transformer-500m-1000g-splice_sites_acceptors-splice_sites_acceptors
sbatch nucleotide-transformer-500m-1000g-splice_sites_donors-splice_sites_donors
sbatch nucleotide-transformer-500m-1000g-H2AFZ-H2AFZ
sbatch nucleotide-transformer-500m-1000g-H3K27ac-H3K27ac
sbatch nucleotide-transformer-500m-1000g-H3K27me3-H3K27me3
sbatch nucleotide-transformer-500m-1000g-H3K36me3-H3K36me3
sbatch nucleotide-transformer-500m-1000g-H3K4me1-H3K4me1
sbatch nucleotide-transformer-500m-1000g-H3K4me2-H3K4me2
sbatch nucleotide-transformer-500m-1000g-H3K4me3-H3K4me3
sbatch nucleotide-transformer-500m-1000g-H3K9ac-H3K9ac
sbatch nucleotide-transformer-500m-1000g-H3K9me3-H3K9me3
sbatch nucleotide-transformer-500m-1000g-H4K20me1-H4K20me1
sbatch nucleotide-transformer-500m-1000g-Genomic_Benchmarks_human_ensembl_regulatory-Genomic_Benchmarks_human_ensembl_regulatory
sbatch nucleotide-transformer-500m-1000g-Genomic_Benchmarks_demo_human_or_worm-Genomic_Benchmarks_demo_human_or_worm
sbatch nucleotide-transformer-500m-1000g-Genomic_Benchmarks_human_ocr_ensembl-Genomic_Benchmarks_human_ocr_ensembl
sbatch nucleotide-transformer-500m-1000g-Genomic_Benchmarks_drosophila_enhancers_stark-Genomic_Benchmarks_drosophila_enhancers_stark
sbatch nucleotide-transformer-500m-1000g-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl
sbatch nucleotide-transformer-500m-1000g-Genomic_Benchmarks_demo_coding_vs_intergenomic_seqs-Genomic_Benchmarks_demo_coding_vs_intergenomic_seqs
sbatch nucleotide-transformer-500m-1000g-Genomic_Benchmarks_human_enhancers_ensembl-Genomic_Benchmarks_human_enhancers_ensembl
sbatch nucleotide-transformer-500m-1000g-Genomic_Benchmarks_human_enhancers_cohn-Genomic_Benchmarks_human_enhancers_cohn
sbatch nucleotide-transformer-500m-1000g-Genomic_Benchmarks_human_nontata_promoters-Genomic_Benchmarks_human_nontata_promoters
sbatch nucleotide-transformer-500m-human-ref-promoter_all-promoter_all
sbatch nucleotide-transformer-500m-human-ref-promoter_tata-promoter_tata
sbatch nucleotide-transformer-500m-human-ref-promoter_no_tata-promoter_no_tata
sbatch nucleotide-transformer-500m-human-ref-enhancers-enhancers
sbatch nucleotide-transformer-500m-human-ref-enhancers_types-enhancers_types
sbatch nucleotide-transformer-500m-human-ref-splice_sites_all-splice_sites_all
sbatch nucleotide-transformer-500m-human-ref-splice_sites_acceptors-splice_sites_acceptors
sbatch nucleotide-transformer-500m-human-ref-splice_sites_donors-splice_sites_donors
sbatch nucleotide-transformer-500m-human-ref-H2AFZ-H2AFZ
sbatch nucleotide-transformer-500m-human-ref-H3K27ac-H3K27ac
sbatch nucleotide-transformer-500m-human-ref-H3K27me3-H3K27me3
sbatch nucleotide-transformer-500m-human-ref-H3K36me3-H3K36me3
sbatch nucleotide-transformer-500m-human-ref-H3K4me1-H3K4me1
sbatch nucleotide-transformer-500m-human-ref-H3K4me2-H3K4me2
sbatch nucleotide-transformer-500m-human-ref-H3K4me3-H3K4me3
sbatch nucleotide-transformer-500m-human-ref-H3K9ac-H3K9ac
sbatch nucleotide-transformer-500m-human-ref-H3K9me3-H3K9me3
sbatch nucleotide-transformer-500m-human-ref-H4K20me1-H4K20me1
sbatch nucleotide-transformer-500m-human-ref-Genomic_Benchmarks_human_ensembl_regulatory-Genomic_Benchmarks_human_ensembl_regulatory
sbatch nucleotide-transformer-500m-human-ref-Genomic_Benchmarks_demo_human_or_worm-Genomic_Benchmarks_demo_human_or_worm
sbatch nucleotide-transformer-500m-human-ref-Genomic_Benchmarks_human_ocr_ensembl-Genomic_Benchmarks_human_ocr_ensembl
sbatch nucleotide-transformer-500m-human-ref-Genomic_Benchmarks_drosophila_enhancers_stark-Genomic_Benchmarks_drosophila_enhancers_stark
sbatch nucleotide-transformer-500m-human-ref-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl
sbatch nucleotide-transformer-500m-human-ref-Genomic_Benchmarks_demo_coding_vs_intergenomic_seqs-Genomic_Benchmarks_demo_coding_vs_intergenomic_seqs
sbatch nucleotide-transformer-500m-human-ref-Genomic_Benchmarks_human_enhancers_ensembl-Genomic_Benchmarks_human_enhancers_ensembl
sbatch nucleotide-transformer-500m-human-ref-Genomic_Benchmarks_human_enhancers_cohn-Genomic_Benchmarks_human_enhancers_cohn
sbatch nucleotide-transformer-500m-human-ref-Genomic_Benchmarks_human_nontata_promoters-Genomic_Benchmarks_human_nontata_promoters
