#!/bin/bash

sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-it01-promoter_all-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-it01-promoter_tata-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-it01-promoter_no_tata-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-it01-enhancers-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-it01-enhancers_types-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-it01-splice_sites_all-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-it01-splice_sites_acceptors-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-it01-splice_sites_donors-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-it01-H2AFZ-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-it01-H3K27ac-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-it01-H3K27me3-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-it01-H3K36me3-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-it01-H3K4me1-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-it01-H3K4me2-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-it01-H3K4me3-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-it01-H3K9ac-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-it01-H3K9me3-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-it01-H4K20me1-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-it01-Genomic_Benchmarks_human_ensembl_regulatory-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-it01-Genomic_Benchmarks_demo_human_or_worm-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-it01-Genomic_Benchmarks_human_ocr_ensembl-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-it01-Genomic_Benchmarks_drosophila_enhancers_stark-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-it01-Genomic_Benchmarks_dummy_mouse_enhancers_ensembl-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-it01-Genomic_Benchmarks_demo_coding_vs_intergenomic_seqs-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-it01-Genomic_Benchmarks_human_enhancers_ensembl-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-it01-Genomic_Benchmarks_human_enhancers_cohn-lora.sh
sbatch jobs/evaluate_mcc/nucleotide-transformer-v2-50m-multi-species-it01-Genomic_Benchmarks_human_nontata_promoters-lora.sh
