#!/bin/bash
cd ..

sbatch jobs/logan/filter/mmseq/mmseqs_0.sh
sbatch jobs/logan/filter/mmseq/mmseqs_1.sh
sbatch jobs/logan/filter/mmseq/mmseqs_10.sh
sbatch jobs/logan/filter/mmseq/mmseqs_100.sh
sbatch jobs/logan/filter/mmseq/mmseqs_101.sh
sbatch jobs/logan/filter/mmseq/mmseqs_102.sh
sbatch jobs/logan/filter/mmseq/mmseqs_103.sh
sbatch jobs/logan/filter/mmseq/mmseqs_104.sh
sbatch jobs/logan/filter/mmseq/mmseqs_105.sh
sbatch jobs/logan/filter/mmseq/mmseqs_106.sh
sbatch jobs/logan/filter/mmseq/mmseqs_107.sh
sbatch jobs/logan/filter/mmseq/mmseqs_108.sh
sbatch jobs/logan/filter/mmseq/mmseqs_109.sh
sbatch jobs/logan/filter/mmseq/mmseqs_11.sh
sbatch jobs/logan/filter/mmseq/mmseqs_110.sh
sbatch jobs/logan/filter/mmseq/mmseqs_111.sh
sbatch jobs/logan/filter/mmseq/mmseqs_112.sh
sbatch jobs/logan/filter/mmseq/mmseqs_113.sh
sbatch jobs/logan/filter/mmseq/mmseqs_115.sh
sbatch jobs/logan/filter/mmseq/mmseqs_116.sh
sbatch jobs/logan/filter/mmseq/mmseqs_117.sh
sbatch jobs/logan/filter/mmseq/mmseqs_118.sh
sbatch jobs/logan/filter/mmseq/mmseqs_119.sh
sbatch jobs/logan/filter/mmseq/mmseqs_12.sh
sbatch jobs/logan/filter/mmseq/mmseqs_122.sh
sbatch jobs/logan/filter/mmseq/mmseqs_123.sh
sbatch jobs/logan/filter/mmseq/mmseqs_125.sh
sbatch jobs/logan/filter/mmseq/mmseqs_126.sh
sbatch jobs/logan/filter/mmseq/mmseqs_127.sh
sbatch jobs/logan/filter/mmseq/mmseqs_128.sh
sbatch jobs/logan/filter/mmseq/mmseqs_129.sh
sbatch jobs/logan/filter/mmseq/mmseqs_13.sh
sbatch jobs/logan/filter/mmseq/mmseqs_130.sh
sbatch jobs/logan/filter/mmseq/mmseqs_131.sh
sbatch jobs/logan/filter/mmseq/mmseqs_132.sh
sbatch jobs/logan/filter/mmseq/mmseqs_133.sh
sbatch jobs/logan/filter/mmseq/mmseqs_134.sh
sbatch jobs/logan/filter/mmseq/mmseqs_135.sh
sbatch jobs/logan/filter/mmseq/mmseqs_136.sh
sbatch jobs/logan/filter/mmseq/mmseqs_137.sh
sbatch jobs/logan/filter/mmseq/mmseqs_138.sh
sbatch jobs/logan/filter/mmseq/mmseqs_139.sh
sbatch jobs/logan/filter/mmseq/mmseqs_14.sh
sbatch jobs/logan/filter/mmseq/mmseqs_141.sh
sbatch jobs/logan/filter/mmseq/mmseqs_142.sh
sbatch jobs/logan/filter/mmseq/mmseqs_143.sh
sbatch jobs/logan/filter/mmseq/mmseqs_144.sh
sbatch jobs/logan/filter/mmseq/mmseqs_145.sh
sbatch jobs/logan/filter/mmseq/mmseqs_146.sh
sbatch jobs/logan/filter/mmseq/mmseqs_147.sh
sbatch jobs/logan/filter/mmseq/mmseqs_148.sh
sbatch jobs/logan/filter/mmseq/mmseqs_149.sh
sbatch jobs/logan/filter/mmseq/mmseqs_15.sh
sbatch jobs/logan/filter/mmseq/mmseqs_150.sh
sbatch jobs/logan/filter/mmseq/mmseqs_151.sh
sbatch jobs/logan/filter/mmseq/mmseqs_152.sh
sbatch jobs/logan/filter/mmseq/mmseqs_154.sh
sbatch jobs/logan/filter/mmseq/mmseqs_155.sh
sbatch jobs/logan/filter/mmseq/mmseqs_156.sh
sbatch jobs/logan/filter/mmseq/mmseqs_157.sh
sbatch jobs/logan/filter/mmseq/mmseqs_159.sh
sbatch jobs/logan/filter/mmseq/mmseqs_16.sh
sbatch jobs/logan/filter/mmseq/mmseqs_160.sh
sbatch jobs/logan/filter/mmseq/mmseqs_161.sh
sbatch jobs/logan/filter/mmseq/mmseqs_162.sh
sbatch jobs/logan/filter/mmseq/mmseqs_163.sh
sbatch jobs/logan/filter/mmseq/mmseqs_165.sh
sbatch jobs/logan/filter/mmseq/mmseqs_167.sh
sbatch jobs/logan/filter/mmseq/mmseqs_168.sh
sbatch jobs/logan/filter/mmseq/mmseqs_169.sh
sbatch jobs/logan/filter/mmseq/mmseqs_17.sh
sbatch jobs/logan/filter/mmseq/mmseqs_171.sh
sbatch jobs/logan/filter/mmseq/mmseqs_173.sh
sbatch jobs/logan/filter/mmseq/mmseqs_174.sh
sbatch jobs/logan/filter/mmseq/mmseqs_175.sh
sbatch jobs/logan/filter/mmseq/mmseqs_176.sh
sbatch jobs/logan/filter/mmseq/mmseqs_177.sh
sbatch jobs/logan/filter/mmseq/mmseqs_179.sh
sbatch jobs/logan/filter/mmseq/mmseqs_18.sh
sbatch jobs/logan/filter/mmseq/mmseqs_180.sh
sbatch jobs/logan/filter/mmseq/mmseqs_181.sh
sbatch jobs/logan/filter/mmseq/mmseqs_183.sh
sbatch jobs/logan/filter/mmseq/mmseqs_186.sh
sbatch jobs/logan/filter/mmseq/mmseqs_187.sh
sbatch jobs/logan/filter/mmseq/mmseqs_188.sh
sbatch jobs/logan/filter/mmseq/mmseqs_189.sh
sbatch jobs/logan/filter/mmseq/mmseqs_19.sh
sbatch jobs/logan/filter/mmseq/mmseqs_191.sh
sbatch jobs/logan/filter/mmseq/mmseqs_192.sh
sbatch jobs/logan/filter/mmseq/mmseqs_193.sh
sbatch jobs/logan/filter/mmseq/mmseqs_194.sh
sbatch jobs/logan/filter/mmseq/mmseqs_195.sh
sbatch jobs/logan/filter/mmseq/mmseqs_196.sh
sbatch jobs/logan/filter/mmseq/mmseqs_197.sh
sbatch jobs/logan/filter/mmseq/mmseqs_198.sh
sbatch jobs/logan/filter/mmseq/mmseqs_199.sh
sbatch jobs/logan/filter/mmseq/mmseqs_2.sh
sbatch jobs/logan/filter/mmseq/mmseqs_20.sh
sbatch jobs/logan/filter/mmseq/mmseqs_200.sh
sbatch jobs/logan/filter/mmseq/mmseqs_201.sh
sbatch jobs/logan/filter/mmseq/mmseqs_204.sh
sbatch jobs/logan/filter/mmseq/mmseqs_205.sh
sbatch jobs/logan/filter/mmseq/mmseqs_206.sh
sbatch jobs/logan/filter/mmseq/mmseqs_207.sh
sbatch jobs/logan/filter/mmseq/mmseqs_208.sh
sbatch jobs/logan/filter/mmseq/mmseqs_209.sh
sbatch jobs/logan/filter/mmseq/mmseqs_21.sh
sbatch jobs/logan/filter/mmseq/mmseqs_210.sh
sbatch jobs/logan/filter/mmseq/mmseqs_211.sh
sbatch jobs/logan/filter/mmseq/mmseqs_212.sh
sbatch jobs/logan/filter/mmseq/mmseqs_213.sh
sbatch jobs/logan/filter/mmseq/mmseqs_214.sh
sbatch jobs/logan/filter/mmseq/mmseqs_217.sh
sbatch jobs/logan/filter/mmseq/mmseqs_218.sh
sbatch jobs/logan/filter/mmseq/mmseqs_219.sh
sbatch jobs/logan/filter/mmseq/mmseqs_220.sh
sbatch jobs/logan/filter/mmseq/mmseqs_221.sh
sbatch jobs/logan/filter/mmseq/mmseqs_222.sh
sbatch jobs/logan/filter/mmseq/mmseqs_223.sh
sbatch jobs/logan/filter/mmseq/mmseqs_224.sh
sbatch jobs/logan/filter/mmseq/mmseqs_225.sh
sbatch jobs/logan/filter/mmseq/mmseqs_226.sh
sbatch jobs/logan/filter/mmseq/mmseqs_227.sh
sbatch jobs/logan/filter/mmseq/mmseqs_229.sh
sbatch jobs/logan/filter/mmseq/mmseqs_23.sh
sbatch jobs/logan/filter/mmseq/mmseqs_231.sh
sbatch jobs/logan/filter/mmseq/mmseqs_233.sh
sbatch jobs/logan/filter/mmseq/mmseqs_234.sh
sbatch jobs/logan/filter/mmseq/mmseqs_235.sh
sbatch jobs/logan/filter/mmseq/mmseqs_236.sh
sbatch jobs/logan/filter/mmseq/mmseqs_237.sh
sbatch jobs/logan/filter/mmseq/mmseqs_238.sh
sbatch jobs/logan/filter/mmseq/mmseqs_239.sh
sbatch jobs/logan/filter/mmseq/mmseqs_24.sh
sbatch jobs/logan/filter/mmseq/mmseqs_241.sh
sbatch jobs/logan/filter/mmseq/mmseqs_242.sh
sbatch jobs/logan/filter/mmseq/mmseqs_244.sh
sbatch jobs/logan/filter/mmseq/mmseqs_245.sh
sbatch jobs/logan/filter/mmseq/mmseqs_246.sh
sbatch jobs/logan/filter/mmseq/mmseqs_247.sh
sbatch jobs/logan/filter/mmseq/mmseqs_248.sh
sbatch jobs/logan/filter/mmseq/mmseqs_249.sh
sbatch jobs/logan/filter/mmseq/mmseqs_25.sh
sbatch jobs/logan/filter/mmseq/mmseqs_251.sh
sbatch jobs/logan/filter/mmseq/mmseqs_252.sh
sbatch jobs/logan/filter/mmseq/mmseqs_253.sh
sbatch jobs/logan/filter/mmseq/mmseqs_254.sh
sbatch jobs/logan/filter/mmseq/mmseqs_255.sh
sbatch jobs/logan/filter/mmseq/mmseqs_257.sh
sbatch jobs/logan/filter/mmseq/mmseqs_258.sh
sbatch jobs/logan/filter/mmseq/mmseqs_259.sh
sbatch jobs/logan/filter/mmseq/mmseqs_26.sh
sbatch jobs/logan/filter/mmseq/mmseqs_260.sh
sbatch jobs/logan/filter/mmseq/mmseqs_261.sh
sbatch jobs/logan/filter/mmseq/mmseqs_262.sh
sbatch jobs/logan/filter/mmseq/mmseqs_263.sh
sbatch jobs/logan/filter/mmseq/mmseqs_265.sh
sbatch jobs/logan/filter/mmseq/mmseqs_266.sh
sbatch jobs/logan/filter/mmseq/mmseqs_267.sh
sbatch jobs/logan/filter/mmseq/mmseqs_268.sh
sbatch jobs/logan/filter/mmseq/mmseqs_269.sh
sbatch jobs/logan/filter/mmseq/mmseqs_27.sh
sbatch jobs/logan/filter/mmseq/mmseqs_270.sh
sbatch jobs/logan/filter/mmseq/mmseqs_272.sh
sbatch jobs/logan/filter/mmseq/mmseqs_273.sh
sbatch jobs/logan/filter/mmseq/mmseqs_275.sh
sbatch jobs/logan/filter/mmseq/mmseqs_278.sh
sbatch jobs/logan/filter/mmseq/mmseqs_279.sh
sbatch jobs/logan/filter/mmseq/mmseqs_28.sh
sbatch jobs/logan/filter/mmseq/mmseqs_280.sh
sbatch jobs/logan/filter/mmseq/mmseqs_282.sh
sbatch jobs/logan/filter/mmseq/mmseqs_285.sh
sbatch jobs/logan/filter/mmseq/mmseqs_286.sh
sbatch jobs/logan/filter/mmseq/mmseqs_287.sh
sbatch jobs/logan/filter/mmseq/mmseqs_288.sh
sbatch jobs/logan/filter/mmseq/mmseqs_289.sh
sbatch jobs/logan/filter/mmseq/mmseqs_29.sh
sbatch jobs/logan/filter/mmseq/mmseqs_290.sh
sbatch jobs/logan/filter/mmseq/mmseqs_291.sh
sbatch jobs/logan/filter/mmseq/mmseqs_292.sh
sbatch jobs/logan/filter/mmseq/mmseqs_293.sh
sbatch jobs/logan/filter/mmseq/mmseqs_295.sh
sbatch jobs/logan/filter/mmseq/mmseqs_296.sh
sbatch jobs/logan/filter/mmseq/mmseqs_297.sh
sbatch jobs/logan/filter/mmseq/mmseqs_299.sh
sbatch jobs/logan/filter/mmseq/mmseqs_3.sh
sbatch jobs/logan/filter/mmseq/mmseqs_30.sh
sbatch jobs/logan/filter/mmseq/mmseqs_300.sh
sbatch jobs/logan/filter/mmseq/mmseqs_301.sh
sbatch jobs/logan/filter/mmseq/mmseqs_302.sh
sbatch jobs/logan/filter/mmseq/mmseqs_303.sh
sbatch jobs/logan/filter/mmseq/mmseqs_304.sh
sbatch jobs/logan/filter/mmseq/mmseqs_305.sh
sbatch jobs/logan/filter/mmseq/mmseqs_306.sh
sbatch jobs/logan/filter/mmseq/mmseqs_307.sh
sbatch jobs/logan/filter/mmseq/mmseqs_309.sh
sbatch jobs/logan/filter/mmseq/mmseqs_31.sh
sbatch jobs/logan/filter/mmseq/mmseqs_310.sh
sbatch jobs/logan/filter/mmseq/mmseqs_311.sh
sbatch jobs/logan/filter/mmseq/mmseqs_312.sh
sbatch jobs/logan/filter/mmseq/mmseqs_313.sh
sbatch jobs/logan/filter/mmseq/mmseqs_315.sh
sbatch jobs/logan/filter/mmseq/mmseqs_316.sh
sbatch jobs/logan/filter/mmseq/mmseqs_317.sh
sbatch jobs/logan/filter/mmseq/mmseqs_318.sh
sbatch jobs/logan/filter/mmseq/mmseqs_319.sh
sbatch jobs/logan/filter/mmseq/mmseqs_32.sh
sbatch jobs/logan/filter/mmseq/mmseqs_320.sh
sbatch jobs/logan/filter/mmseq/mmseqs_321.sh
sbatch jobs/logan/filter/mmseq/mmseqs_322.sh
sbatch jobs/logan/filter/mmseq/mmseqs_323.sh
sbatch jobs/logan/filter/mmseq/mmseqs_325.sh
sbatch jobs/logan/filter/mmseq/mmseqs_326.sh
sbatch jobs/logan/filter/mmseq/mmseqs_327.sh
sbatch jobs/logan/filter/mmseq/mmseqs_328.sh
sbatch jobs/logan/filter/mmseq/mmseqs_33.sh
sbatch jobs/logan/filter/mmseq/mmseqs_330.sh
sbatch jobs/logan/filter/mmseq/mmseqs_331.sh
sbatch jobs/logan/filter/mmseq/mmseqs_332.sh
sbatch jobs/logan/filter/mmseq/mmseqs_333.sh
sbatch jobs/logan/filter/mmseq/mmseqs_334.sh
sbatch jobs/logan/filter/mmseq/mmseqs_335.sh
sbatch jobs/logan/filter/mmseq/mmseqs_336.sh
sbatch jobs/logan/filter/mmseq/mmseqs_339.sh
sbatch jobs/logan/filter/mmseq/mmseqs_34.sh
sbatch jobs/logan/filter/mmseq/mmseqs_340.sh
sbatch jobs/logan/filter/mmseq/mmseqs_341.sh
sbatch jobs/logan/filter/mmseq/mmseqs_342.sh
sbatch jobs/logan/filter/mmseq/mmseqs_345.sh
sbatch jobs/logan/filter/mmseq/mmseqs_346.sh
sbatch jobs/logan/filter/mmseq/mmseqs_348.sh
sbatch jobs/logan/filter/mmseq/mmseqs_35.sh
sbatch jobs/logan/filter/mmseq/mmseqs_351.sh
sbatch jobs/logan/filter/mmseq/mmseqs_352.sh
sbatch jobs/logan/filter/mmseq/mmseqs_353.sh
sbatch jobs/logan/filter/mmseq/mmseqs_354.sh
sbatch jobs/logan/filter/mmseq/mmseqs_355.sh
sbatch jobs/logan/filter/mmseq/mmseqs_356.sh
sbatch jobs/logan/filter/mmseq/mmseqs_358.sh
sbatch jobs/logan/filter/mmseq/mmseqs_359.sh
sbatch jobs/logan/filter/mmseq/mmseqs_36.sh
sbatch jobs/logan/filter/mmseq/mmseqs_360.sh
sbatch jobs/logan/filter/mmseq/mmseqs_361.sh
sbatch jobs/logan/filter/mmseq/mmseqs_362.sh
sbatch jobs/logan/filter/mmseq/mmseqs_363.sh
sbatch jobs/logan/filter/mmseq/mmseqs_364.sh
sbatch jobs/logan/filter/mmseq/mmseqs_365.sh
sbatch jobs/logan/filter/mmseq/mmseqs_366.sh
sbatch jobs/logan/filter/mmseq/mmseqs_367.sh
sbatch jobs/logan/filter/mmseq/mmseqs_368.sh
sbatch jobs/logan/filter/mmseq/mmseqs_369.sh
sbatch jobs/logan/filter/mmseq/mmseqs_37.sh
sbatch jobs/logan/filter/mmseq/mmseqs_370.sh
sbatch jobs/logan/filter/mmseq/mmseqs_371.sh
sbatch jobs/logan/filter/mmseq/mmseqs_373.sh
sbatch jobs/logan/filter/mmseq/mmseqs_374.sh
sbatch jobs/logan/filter/mmseq/mmseqs_375.sh
sbatch jobs/logan/filter/mmseq/mmseqs_376.sh
sbatch jobs/logan/filter/mmseq/mmseqs_377.sh
sbatch jobs/logan/filter/mmseq/mmseqs_378.sh
sbatch jobs/logan/filter/mmseq/mmseqs_379.sh
sbatch jobs/logan/filter/mmseq/mmseqs_38.sh
sbatch jobs/logan/filter/mmseq/mmseqs_380.sh
sbatch jobs/logan/filter/mmseq/mmseqs_382.sh
sbatch jobs/logan/filter/mmseq/mmseqs_383.sh
sbatch jobs/logan/filter/mmseq/mmseqs_384.sh
sbatch jobs/logan/filter/mmseq/mmseqs_386.sh
sbatch jobs/logan/filter/mmseq/mmseqs_388.sh
sbatch jobs/logan/filter/mmseq/mmseqs_389.sh
sbatch jobs/logan/filter/mmseq/mmseqs_39.sh
sbatch jobs/logan/filter/mmseq/mmseqs_390.sh
sbatch jobs/logan/filter/mmseq/mmseqs_391.sh
sbatch jobs/logan/filter/mmseq/mmseqs_394.sh
sbatch jobs/logan/filter/mmseq/mmseqs_395.sh
sbatch jobs/logan/filter/mmseq/mmseqs_396.sh
sbatch jobs/logan/filter/mmseq/mmseqs_397.sh
sbatch jobs/logan/filter/mmseq/mmseqs_398.sh
sbatch jobs/logan/filter/mmseq/mmseqs_399.sh
sbatch jobs/logan/filter/mmseq/mmseqs_4.sh
sbatch jobs/logan/filter/mmseq/mmseqs_40.sh
sbatch jobs/logan/filter/mmseq/mmseqs_400.sh
sbatch jobs/logan/filter/mmseq/mmseqs_401.sh
sbatch jobs/logan/filter/mmseq/mmseqs_402.sh
sbatch jobs/logan/filter/mmseq/mmseqs_403.sh
sbatch jobs/logan/filter/mmseq/mmseqs_404.sh
sbatch jobs/logan/filter/mmseq/mmseqs_405.sh
sbatch jobs/logan/filter/mmseq/mmseqs_407.sh
sbatch jobs/logan/filter/mmseq/mmseqs_408.sh
sbatch jobs/logan/filter/mmseq/mmseqs_41.sh
sbatch jobs/logan/filter/mmseq/mmseqs_410.sh
sbatch jobs/logan/filter/mmseq/mmseqs_411.sh
sbatch jobs/logan/filter/mmseq/mmseqs_412.sh
sbatch jobs/logan/filter/mmseq/mmseqs_413.sh
sbatch jobs/logan/filter/mmseq/mmseqs_414.sh
sbatch jobs/logan/filter/mmseq/mmseqs_417.sh
sbatch jobs/logan/filter/mmseq/mmseqs_418.sh
sbatch jobs/logan/filter/mmseq/mmseqs_42.sh
sbatch jobs/logan/filter/mmseq/mmseqs_420.sh
sbatch jobs/logan/filter/mmseq/mmseqs_421.sh
sbatch jobs/logan/filter/mmseq/mmseqs_422.sh
sbatch jobs/logan/filter/mmseq/mmseqs_423.sh
sbatch jobs/logan/filter/mmseq/mmseqs_424.sh
sbatch jobs/logan/filter/mmseq/mmseqs_425.sh
sbatch jobs/logan/filter/mmseq/mmseqs_426.sh
sbatch jobs/logan/filter/mmseq/mmseqs_427.sh
sbatch jobs/logan/filter/mmseq/mmseqs_428.sh
sbatch jobs/logan/filter/mmseq/mmseqs_429.sh
sbatch jobs/logan/filter/mmseq/mmseqs_43.sh
sbatch jobs/logan/filter/mmseq/mmseqs_430.sh
sbatch jobs/logan/filter/mmseq/mmseqs_432.sh
sbatch jobs/logan/filter/mmseq/mmseqs_433.sh
sbatch jobs/logan/filter/mmseq/mmseqs_434.sh
sbatch jobs/logan/filter/mmseq/mmseqs_435.sh
sbatch jobs/logan/filter/mmseq/mmseqs_436.sh
sbatch jobs/logan/filter/mmseq/mmseqs_437.sh
sbatch jobs/logan/filter/mmseq/mmseqs_438.sh
sbatch jobs/logan/filter/mmseq/mmseqs_44.sh
sbatch jobs/logan/filter/mmseq/mmseqs_440.sh
sbatch jobs/logan/filter/mmseq/mmseqs_441.sh
sbatch jobs/logan/filter/mmseq/mmseqs_442.sh
sbatch jobs/logan/filter/mmseq/mmseqs_443.sh
sbatch jobs/logan/filter/mmseq/mmseqs_446.sh
sbatch jobs/logan/filter/mmseq/mmseqs_447.sh
sbatch jobs/logan/filter/mmseq/mmseqs_449.sh
sbatch jobs/logan/filter/mmseq/mmseqs_45.sh
sbatch jobs/logan/filter/mmseq/mmseqs_453.sh
sbatch jobs/logan/filter/mmseq/mmseqs_454.sh
sbatch jobs/logan/filter/mmseq/mmseqs_456.sh
sbatch jobs/logan/filter/mmseq/mmseqs_457.sh
sbatch jobs/logan/filter/mmseq/mmseqs_458.sh
sbatch jobs/logan/filter/mmseq/mmseqs_459.sh
sbatch jobs/logan/filter/mmseq/mmseqs_46.sh
sbatch jobs/logan/filter/mmseq/mmseqs_461.sh
sbatch jobs/logan/filter/mmseq/mmseqs_462.sh
sbatch jobs/logan/filter/mmseq/mmseqs_463.sh
sbatch jobs/logan/filter/mmseq/mmseqs_464.sh
sbatch jobs/logan/filter/mmseq/mmseqs_468.sh
sbatch jobs/logan/filter/mmseq/mmseqs_469.sh
sbatch jobs/logan/filter/mmseq/mmseqs_47.sh
sbatch jobs/logan/filter/mmseq/mmseqs_470.sh
sbatch jobs/logan/filter/mmseq/mmseqs_471.sh
sbatch jobs/logan/filter/mmseq/mmseqs_472.sh
sbatch jobs/logan/filter/mmseq/mmseqs_473.sh
sbatch jobs/logan/filter/mmseq/mmseqs_474.sh
sbatch jobs/logan/filter/mmseq/mmseqs_476.sh
sbatch jobs/logan/filter/mmseq/mmseqs_477.sh
sbatch jobs/logan/filter/mmseq/mmseqs_478.sh
sbatch jobs/logan/filter/mmseq/mmseqs_48.sh
sbatch jobs/logan/filter/mmseq/mmseqs_480.sh
sbatch jobs/logan/filter/mmseq/mmseqs_481.sh
sbatch jobs/logan/filter/mmseq/mmseqs_482.sh
sbatch jobs/logan/filter/mmseq/mmseqs_483.sh
sbatch jobs/logan/filter/mmseq/mmseqs_484.sh
sbatch jobs/logan/filter/mmseq/mmseqs_485.sh
sbatch jobs/logan/filter/mmseq/mmseqs_488.sh
sbatch jobs/logan/filter/mmseq/mmseqs_489.sh
sbatch jobs/logan/filter/mmseq/mmseqs_49.sh
sbatch jobs/logan/filter/mmseq/mmseqs_490.sh
sbatch jobs/logan/filter/mmseq/mmseqs_491.sh
sbatch jobs/logan/filter/mmseq/mmseqs_492.sh
sbatch jobs/logan/filter/mmseq/mmseqs_493.sh
sbatch jobs/logan/filter/mmseq/mmseqs_494.sh
sbatch jobs/logan/filter/mmseq/mmseqs_495.sh
sbatch jobs/logan/filter/mmseq/mmseqs_496.sh
sbatch jobs/logan/filter/mmseq/mmseqs_497.sh
sbatch jobs/logan/filter/mmseq/mmseqs_498.sh
sbatch jobs/logan/filter/mmseq/mmseqs_499.sh
sbatch jobs/logan/filter/mmseq/mmseqs_5.sh
sbatch jobs/logan/filter/mmseq/mmseqs_50.sh
sbatch jobs/logan/filter/mmseq/mmseqs_51.sh
sbatch jobs/logan/filter/mmseq/mmseqs_52.sh
sbatch jobs/logan/filter/mmseq/mmseqs_53.sh
sbatch jobs/logan/filter/mmseq/mmseqs_54.sh
sbatch jobs/logan/filter/mmseq/mmseqs_55.sh
sbatch jobs/logan/filter/mmseq/mmseqs_56.sh
sbatch jobs/logan/filter/mmseq/mmseqs_57.sh
sbatch jobs/logan/filter/mmseq/mmseqs_58.sh
sbatch jobs/logan/filter/mmseq/mmseqs_59.sh
sbatch jobs/logan/filter/mmseq/mmseqs_6.sh
sbatch jobs/logan/filter/mmseq/mmseqs_62.sh
sbatch jobs/logan/filter/mmseq/mmseqs_63.sh
sbatch jobs/logan/filter/mmseq/mmseqs_64.sh
sbatch jobs/logan/filter/mmseq/mmseqs_65.sh
sbatch jobs/logan/filter/mmseq/mmseqs_66.sh
sbatch jobs/logan/filter/mmseq/mmseqs_67.sh
sbatch jobs/logan/filter/mmseq/mmseqs_68.sh
sbatch jobs/logan/filter/mmseq/mmseqs_69.sh
sbatch jobs/logan/filter/mmseq/mmseqs_7.sh
sbatch jobs/logan/filter/mmseq/mmseqs_70.sh
sbatch jobs/logan/filter/mmseq/mmseqs_71.sh
sbatch jobs/logan/filter/mmseq/mmseqs_72.sh
sbatch jobs/logan/filter/mmseq/mmseqs_73.sh
sbatch jobs/logan/filter/mmseq/mmseqs_74.sh
sbatch jobs/logan/filter/mmseq/mmseqs_75.sh
sbatch jobs/logan/filter/mmseq/mmseqs_76.sh
sbatch jobs/logan/filter/mmseq/mmseqs_77.sh
sbatch jobs/logan/filter/mmseq/mmseqs_78.sh
sbatch jobs/logan/filter/mmseq/mmseqs_79.sh
sbatch jobs/logan/filter/mmseq/mmseqs_8.sh
sbatch jobs/logan/filter/mmseq/mmseqs_80.sh
sbatch jobs/logan/filter/mmseq/mmseqs_81.sh
sbatch jobs/logan/filter/mmseq/mmseqs_82.sh
sbatch jobs/logan/filter/mmseq/mmseqs_83.sh
sbatch jobs/logan/filter/mmseq/mmseqs_84.sh
sbatch jobs/logan/filter/mmseq/mmseqs_87.sh
sbatch jobs/logan/filter/mmseq/mmseqs_89.sh
sbatch jobs/logan/filter/mmseq/mmseqs_9.sh
sbatch jobs/logan/filter/mmseq/mmseqs_92.sh
sbatch jobs/logan/filter/mmseq/mmseqs_93.sh
sbatch jobs/logan/filter/mmseq/mmseqs_94.sh
sbatch jobs/logan/filter/mmseq/mmseqs_95.sh
sbatch jobs/logan/filter/mmseq/mmseqs_96.sh
sbatch jobs/logan/filter/mmseq/mmseqs_97.sh
sbatch jobs/logan/filter/mmseq/mmseqs_98.sh
sbatch jobs/logan/filter/mmseq/mmseqs_99.sh
