#!/bin/bash
cd ..

sbatch jobs/logan/filter/mmseq95/mmseqs_1.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_94.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_135.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_7.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_362.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_38.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_263.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_97.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_87.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_327.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_309.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_426.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_469.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_193.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_102.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_41.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_301.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_404.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_66.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_401.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_463.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_435.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_268.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_198.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_199.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_28.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_39.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_390.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_391.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_394.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_395.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_396.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_397.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_398.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_399.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_4.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_40.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_400.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_402.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_403.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_405.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_407.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_408.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_410.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_411.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_412.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_413.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_414.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_417.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_418.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_42.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_420.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_421.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_422.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_423.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_424.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_425.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_427.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_428.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_429.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_43.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_430.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_432.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_433.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_434.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_436.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_437.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_438.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_44.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_440.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_441.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_442.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_443.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_446.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_447.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_449.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_45.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_453.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_454.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_456.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_457.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_458.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_459.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_46.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_461.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_462.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_464.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_468.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_47.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_470.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_471.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_472.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_473.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_474.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_476.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_477.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_478.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_48.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_480.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_481.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_482.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_483.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_484.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_485.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_488.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_489.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_49.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_490.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_491.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_492.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_493.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_494.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_495.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_496.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_497.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_498.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_499.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_5.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_50.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_51.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_52.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_53.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_54.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_55.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_56.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_57.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_58.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_59.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_6.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_62.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_63.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_64.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_65.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_67.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_68.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_69.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_70.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_71.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_72.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_73.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_74.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_75.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_76.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_77.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_78.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_79.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_8.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_80.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_81.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_82.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_83.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_84.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_89.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_9.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_92.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_93.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_95.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_96.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_98.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_99.sh
