#!/bin/bash
cd ..

sbatch jobs/logan/filter/mmseq95/mmseqs_1.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_4.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_5.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_6.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_7.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_9.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_28.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_38.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_39.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_40.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_42.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_48.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_50.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_53.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_54.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_55.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_58.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_65.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_71.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_74.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_75.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_80.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_81.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_92.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_93.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_94.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_97.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_99.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_135.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_198.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_199.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_362.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_394.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_395.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_396.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_397.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_399.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_400.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_402.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_405.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_407.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_408.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_410.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_412.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_414.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_417.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_418.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_421.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_422.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_424.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_425.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_427.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_432.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_434.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_435.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_447.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_449.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_454.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_457.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_472.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_474.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_476.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_478.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_482.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_483.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_484.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_489.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_490.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_491.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_492.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_493.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_495.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_496.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_497.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_498.sh
sbatch jobs/logan/filter/mmseq95/mmseqs_499.sh
