import os
from config import datasets_cache_dir

TASKS = [
    {'taskId': 1,'repo': "InstaDeepAI/nucleotide_transformer_downstream_tasks_revised", 'name': "promoter_all", 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 2},
    {'taskId': 2,'repo': "InstaDeepAI/nucleotide_transformer_downstream_tasks_revised", 'name': "promoter_tata", 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 2},
    {'taskId': 3,'repo': "InstaDeepAI/nucleotide_transformer_downstream_tasks_revised", 'name': "promoter_no_tata", 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 2},
    {'taskId': 4,'repo': "InstaDeepAI/nucleotide_transformer_downstream_tasks_revised", 'name': "enhancers", 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 2},
    {'taskId': 5,'repo': "InstaDeepAI/nucleotide_transformer_downstream_tasks_revised", 'name': "enhancers_types", 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 3},
    {'taskId': 6,'repo': "InstaDeepAI/nucleotide_transformer_downstream_tasks_revised", 'name': "splice_sites_all", 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 3},
    {'taskId': 7,'repo': "InstaDeepAI/nucleotide_transformer_downstream_tasks_revised", 'name': "splice_sites_acceptors", 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 2},
    {'taskId': 8,'repo': "InstaDeepAI/nucleotide_transformer_downstream_tasks_revised", 'name': "splice_sites_donors", 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 2},
    {'taskId': 9,'repo': "InstaDeepAI/nucleotide_transformer_downstream_tasks_revised", 'name': "H2AFZ", 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 2},
    {'taskId': 10,'repo': "InstaDeepAI/nucleotide_transformer_downstream_tasks_revised", 'name': "H3K27ac", 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 2},
    {'taskId': 11,'repo': "InstaDeepAI/nucleotide_transformer_downstream_tasks_revised", 'name': "H3K27me3", 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 2},
    {'taskId': 12,'repo': "InstaDeepAI/nucleotide_transformer_downstream_tasks_revised", 'name': "H3K36me3", 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 2},
    {'taskId': 13,'repo': "InstaDeepAI/nucleotide_transformer_downstream_tasks_revised", 'name': "H3K4me1", 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 2},
    {'taskId': 14,'repo': "InstaDeepAI/nucleotide_transformer_downstream_tasks_revised", 'name': "H3K4me2", 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 2},
    {'taskId': 15,'repo': "InstaDeepAI/nucleotide_transformer_downstream_tasks_revised", 'name': "H3K4me3", 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 2},
    {'taskId': 16,'repo': "InstaDeepAI/nucleotide_transformer_downstream_tasks_revised", 'name': "H3K9ac", 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 2},
    {'taskId': 17,'repo': "InstaDeepAI/nucleotide_transformer_downstream_tasks_revised", 'name': "H3K9me3", 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 2},
    {'taskId': 18,'repo': "InstaDeepAI/nucleotide_transformer_downstream_tasks_revised", 'name': "H4K20me1", 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 2},
    {'taskId': 19,'repo': "katarinagresova/Genomic_Benchmarks_human_ensembl_regulatory", 'name': "gb_human_ensembl_regulatory", 'sequence_feature': 'seq', 'label_feature': 'label', 'num_labels': 3},
    {'taskId': 20,'repo': "katarinagresova/Genomic_Benchmarks_demo_human_or_worm", 'name': "gb_demo_human_or_worm", 'sequence_feature': 'seq', 'label_feature': 'label', 'num_labels': 2},
    {'taskId': 21,'repo': "katarinagresova/Genomic_Benchmarks_human_ocr_ensembl", 'name': "gb_human_ocr_ensembl", 'sequence_feature': 'seq', 'label_feature': 'label', 'num_labels': 2},
    {'taskId': 22,'repo': "katarinagresova/Genomic_Benchmarks_drosophila_enhancers_stark", 'name': "gb_drosophila_enhancers_stark", 'sequence_feature': 'seq', 'label_feature': 'label', 'num_labels': 2},
    {'taskId': 23,'repo': "katarinagresova/Genomic_Benchmarks_dummy_mouse_enhancers_ensembl", 'name': "gb_dummy_mouse_enhancers_ensembl", 'sequence_feature': 'seq', 'label_feature': 'label', 'num_labels': 2},
    {'taskId': 24,'repo': "katarinagresova/Genomic_Benchmarks_demo_coding_vs_intergenomic_seqs", 'name': "gb_demo_coding_vs_intergenomic_seqs", 'sequence_feature': 'seq', 'label_feature': 'label', 'num_labels': 2},
    {'taskId': 25,'repo': "katarinagresova/Genomic_Benchmarks_human_enhancers_ensembl", 'name': "gb_human_enhancers_ensembl", 'sequence_feature': 'seq', 'label_feature': 'label', 'num_labels': 2},
    {'taskId': 26,'repo': "katarinagresova/Genomic_Benchmarks_human_enhancers_cohn", 'name': "gb_human_enhancers_cohn", 'sequence_feature': 'seq', 'label_feature': 'label', 'num_labels': 2},
    {'taskId': 27,'repo': "katarinagresova/Genomic_Benchmarks_human_nontata_promoters", 'name': "gb_human_nontata_promoters", 'sequence_feature': 'seq', 'label_feature': 'label', 'num_labels': 2},
    {'taskId': 28,'repo': os.path.join(datasets_cache_dir, '5_utr_classification'), 'name': "utr5_ben_pat", 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 2},
    {'taskId': 29,'repo': os.path.join(datasets_cache_dir, '5_utr_classification_fixed_1000'), 'name': "utr5_ben_pat_fixed", 'sequence_feature': 'sequence', 'label_feature': 'label', 'num_labels': 2}
]

MODELS = [
    {'name': 'default_multi_species_untrained', 'dataset': 'multi_species', 'tokenizer': 'default', 'context': '1', 'ewc': False, 'ewc_lambda': None, 'pca': False, 'pca_dim': None, 'pca_embed': None, 'sharon': None, 'gc': None},
    {'name': 'default_multi_species_untrained_100', 'dataset': 'multi_species', 'tokenizer': 'default', 'context': '1', 'ewc': False, 'ewc_lambda': None, 'pca': False, 'pca_dim': None, 'pca_embed': None, 'sharon': None, 'gc': None},
    {'name': 'default_multi_species_untrained_250', 'dataset': 'multi_species', 'tokenizer': 'default', 'context': '1', 'ewc': False, 'ewc_lambda': None, 'pca': False, 'pca_dim': None, 'pca_embed': None, 'sharon': None, 'gc': None},
    {'name': 'default_multi_species_untrained_500', 'dataset': 'multi_species', 'tokenizer': 'default', 'context': '1', 'ewc': False, 'ewc_lambda': None, 'pca': False, 'pca_dim': None, 'pca_embed': None, 'sharon': None, 'gc': None},
    {'name': 'default_multi_species_untrained_500_tg', 'dataset': 'multi_species', 'tokenizer': 'default', 'context': '1', 'ewc': False, 'ewc_lambda': None, 'pca': False, 'pca_dim': None, 'pca_embed': None, 'sharon': None, 'gc': None},
    {'name': 'default_multi_species_untrained_500_human', 'dataset': 'multi_species', 'tokenizer': 'default', 'context': '1', 'ewc': False, 'ewc_lambda': None, 'pca': False, 'pca_dim': None, 'pca_embed': None, 'sharon': None, 'gc': None},
    {'name': 'default_multi_species', 'dataset': 'multi_species', 'tokenizer': 'default', 'context': '1', 'ewc': False, 'ewc_lambda': None, 'pca': False, 'pca_dim': None, 'pca_embed': None, 'sharon': None, 'gc': None},
    {'name': 'default_multi_species_2kb', 'dataset': 'multi_species', 'tokenizer': 'default', 'context': '2', 'ewc': False, 'ewc_lambda': None, 'pca': False, 'pca_dim': None, 'pca_embed': None, 'sharon': None, 'gc': None},
    {'name': 'overlap_multi_species', 'dataset': 'multi_species', 'tokenizer': 'overlapping', 'context': '1', 'ewc': False, 'ewc_lambda': None, 'pca': False, 'pca_dim': None, 'pca_embed': None, 'sharon': None, 'gc': None},
    {'name': 'overlap_multi_species_2kb', 'dataset': 'multi_species', 'tokenizer': 'overlapping', 'context': '2', 'ewc': False, 'ewc_lambda': None, 'pca': False, 'pca_dim': None, 'pca_embed': None, 'sharon': None, 'gc': None},
    {'name': 'overlap_logan_no_ewc', 'dataset': 'logan', 'tokenizer': 'overlapping', 'context': '2', 'ewc': False, 'ewc_lambda': None, 'pca': False, 'pca_dim': None, 'pca_embed': None, 'sharon': None, 'gc': None},
    {'name': 'overlap_logan_ewc_0_5', 'dataset': 'logan', 'tokenizer': 'overlapping', 'context': '2', 'ewc': True, 'ewc_lambda': 0.5, 'pca': False, 'pca_dim': None, 'pca_embed': None, 'sharon': None, 'gc': None},
    {'name': 'overlap_logan_ewc_1', 'dataset': 'logan', 'tokenizer': 'overlapping', 'context': '2', 'ewc': True, 'ewc_lambda': 1, 'pca': False, 'pca_dim': None, 'pca_embed': None, 'sharon': None, 'gc': None},
    {'name': 'overlap_logan_ewc_2', 'dataset': 'logan', 'tokenizer': 'overlapping', 'context': '2', 'ewc': True, 'ewc_lambda': 2, 'pca': False, 'pca_dim': None, 'pca_embed': None, 'sharon': None, 'gc': None},
    {'name': 'overlap_logan_ewc_5', 'dataset': 'logan', 'tokenizer': 'overlapping', 'context': '2', 'ewc': True, 'ewc_lambda': 5, 'pca': False, 'pca_dim': None, 'pca_embed': None, 'sharon': None, 'gc': None},
    {'name': 'overlap_logan_ewc_10', 'dataset': 'logan', 'tokenizer': 'overlapping', 'context': '2', 'ewc': True, 'ewc_lambda': 10, 'pca': False, 'pca_dim': None, 'pca_embed': None, 'sharon': None, 'gc': None},
    {'name': 'overlap_logan_ewc_25', 'dataset': 'logan', 'tokenizer': 'overlapping', 'context': '2', 'ewc': True, 'ewc_lambda': 25, 'pca': False, 'pca_dim': None, 'pca_embed': None, 'sharon': None, 'gc': None},
    {'name': 'default_multi_species_sh_gc', 'dataset': 'multi_species', 'tokenizer': 'default', 'context': '1', 'ewc': False, 'ewc_lambda': None, 'pca': False, 'pca_dim': None, 'pca_embed': None, 'sharon': '1.35-1.8', 'gc': '0.4-0.6'},
    {'name': 'default_multi_species_2kb_sh_gc', 'dataset': 'multi_species', 'tokenizer': 'default', 'context': '2', 'ewc': False, 'ewc_lambda': None, 'pca': False, 'pca_dim': None, 'pca_embed': None, 'sharon': '1.35-1.8', 'gc': '0.4-0.6'},
    {'name': 'overlap_multi_species_sh_gc', 'dataset': 'multi_species', 'tokenizer': 'overlapping', 'context': '1', 'ewc': False, 'ewc_lambda': None, 'pca': False, 'pca_dim': None, 'pca_embed': None, 'sharon': '1.35-1.8', 'gc': '0.4-0.6'},
    {'name': 'overlap_multi_species_2kb_sh_gc', 'dataset': 'multi_species', 'tokenizer': 'overlapping', 'context': '2', 'ewc': False, 'ewc_lambda': None, 'pca': False, 'pca_dim': None, 'pca_embed': None, 'sharon': '1.35-1.8', 'gc': '0.4-0.6'},
    {'name': 'overlap_multi_species_pca_cls_256', 'dataset': 'multi_species', 'tokenizer': 'overlapping', 'context': '1', 'ewc': False, 'ewc_lambda': None, 'pca': True, 'pca_dim': 256, 'pca_embed': 'CLS', 'sharon': None, 'gc': None},
    {'name': 'overlap_multi_species_pca_mean_256', 'dataset': 'multi_species', 'tokenizer': 'overlapping', 'context': '1', 'ewc': False, 'ewc_lambda': None, 'pca': True, 'pca_dim': 256, 'pca_embed': 'mean', 'sharon': None, 'gc': None},
]

TASK_DEFINITIONS = [
    {'name': 'promoter_all', 'alias': 'Promoter (all)'},
    {'name': 'promoter_tata', 'alias': 'Promoter (TATA)'},
    {'name': 'promoter_no_tata', 'alias': 'Promoter (non-TATA)'},
    {'name': 'enhancers', 'alias': 'Enhancers'},
    {'name': 'enhancers_types', 'alias': 'Enhancers (types)'},
    {'name': 'splice_sites_all', 'alias': 'Splice Sites (all)'},
    {'name': 'splice_sites_acceptors', 'alias': 'Splice Sites (acceptors)'},
    {'name': 'splice_sites_donors', 'alias': 'Splice Sites (donors)'},
    {'name': 'H2AFZ', 'alias': 'H2AFZ'},
    {'name': 'H3K27ac', 'alias': 'H3K27ac'},
    {'name': 'H3K27me3', 'alias': 'H3K27me3'},
    {'name': 'H3K36me3', 'alias': 'H3K36me3'},
    {'name': 'H3K4me1', 'alias': 'H3K4me1'},
    {'name': 'H3K4me2', 'alias': 'H3K4me2'},
    {'name': 'H3K4me3', 'alias': 'H3K4me3'},
    {'name': 'H3K9ac', 'alias': 'H3K9ac'},
    {'name': 'H3K9me3', 'alias': 'H3K9me3'},
    {'name': 'H4K20me1', 'alias': 'H4K20me1'},
    {'name': 'gb_human_ensembl_regulatory', 'alias': 'Human Ensemble (regulatory)'},
    {'name': 'gb_demo_human_or_worm', 'alias': 'Human or Worm (Demo)'},
    {'name': 'gb_human_ocr_ensembl', 'alias': 'Human Ensemble (ocr)'},
    {'name': 'gb_drosophila_enhancers_stark', 'alias': 'Enhancers (drosophila)'},
    {'name': 'gb_dummy_mouse_enhancers_ensembl', 'alias': 'Enhancers (mouse)'},
    {'name': 'gb_demo_coding_vs_intergenomic_seqs', 'alias': 'Coding vs Intergen. Seq.'},
    {'name': 'gb_human_enhancers_ensembl', 'alias': 'Enh. (human ensemble)'},
    {'name': 'gb_human_enhancers_cohn', 'alias': 'Enh. (human cohn)'},
    {'name': 'gb_human_nontata_promoters', 'alias': 'Prom. Human (no TATA)'}
]